`default_nettype none
module __t__matrix_loader_send_0_next(
  input wire clk,
  input wire rst,
  input wire [31:0] t__cur_row_partition,
  input wire t__cur_row_partition_vld,
  input wire t__metadata_addr_rdy,
  input wire [159:0] t__metadata_payload,
  input wire t__metadata_payload_vld,
  input wire [31:0] t__num_col_partitions,
  input wire t__num_col_partitions_vld,
  input wire t__streaming_addr_rdy,
  input wire [31:0] t__tot_num_partitions,
  input wire t__tot_num_partitions_vld,
  output wire t__cur_row_partition_rdy,
  output wire [63:0] t__metadata_addr,
  output wire t__metadata_addr_vld,
  output wire t__metadata_payload_rdy,
  output wire t__num_col_partitions_rdy,
  output wire [63:0] t__streaming_addr,
  output wire t__streaming_addr_vld,
  output wire t__tot_num_partitions_rdy
);
  // lint_off MULTIPLY
  function automatic [30:0] umul31b_31b_x_31b (input reg [30:0] lhs, input reg [30:0] rhs);
    begin
      umul31b_31b_x_31b = lhs * rhs;
    end
  endfunction
  // lint_on MULTIPLY
  wire [159:0] __t__metadata_payload_reg_init = {{64'h0000_0000_0000_0000, 64'h0000_0000_0000_0000}, 2'h0, 30'h0000_0000};
  wire [159:0] __t__metadata_payload_skid_reg_init = {{64'h0000_0000_0000_0000, 64'h0000_0000_0000_0000}, 2'h0, 30'h0000_0000};
  wire [63:0] __t__metadata_addr_reg_init = {32'h0000_0000, 2'h0, 30'h0000_0000};
  wire [63:0] __t__streaming_addr_reg_init = {32'h0000_0000, 2'h0, 30'h0000_0000};
  wire [159:0] literal_2303 = {{64'h0000_0000_0000_0000, 64'h0000_0000_0000_0000}, 2'h0, 30'h0000_0000};
  reg [4:0] ____state_0;
  reg [31:0] ____state_3;
  reg [31:0] ____state_5;
  reg [31:0] ____state_8;
  reg [31:0] ____state_1;
  reg [31:0] ____state_2;
  reg [31:0] ____state_10;
  reg [31:0] ____state_7;
  reg [31:0] ____state_4;
  reg ____state_11;
  reg __t__metadata_addr_has_been_sent_reg;
  reg __t__streaming_addr_has_been_sent_reg;
  reg [159:0] __t__metadata_payload_reg;
  reg [159:0] __t__metadata_payload_skid_reg;
  reg __t__metadata_payload_valid_reg;
  reg __t__metadata_payload_valid_skid_reg;
  reg [31:0] __t__cur_row_partition_reg;
  reg [31:0] __t__cur_row_partition_skid_reg;
  reg __t__cur_row_partition_valid_reg;
  reg __t__cur_row_partition_valid_skid_reg;
  reg [31:0] __t__num_col_partitions_reg;
  reg [31:0] __t__num_col_partitions_skid_reg;
  reg __t__num_col_partitions_valid_reg;
  reg __t__num_col_partitions_valid_skid_reg;
  reg [31:0] __t__tot_num_partitions_reg;
  reg [31:0] __t__tot_num_partitions_skid_reg;
  reg __t__tot_num_partitions_valid_reg;
  reg __t__tot_num_partitions_valid_skid_reg;
  reg [63:0] __t__metadata_addr_reg;
  reg __t__metadata_addr_valid_reg;
  reg [63:0] __t__streaming_addr_reg;
  reg __t__streaming_addr_valid_reg;
  wire [4:0] unexpand_for_next_value_519_0__1_case_1;
  wire st7_2_case_cmp;
  wire eq_2299;
  wire [4:0] unexpand_for_next_value_519_0__1_case_6_case_1;
  wire [4:0] unexpand_for_next_value_519_0__1_case_4_case_1;
  wire [4:0] unexpand_for_next_value_519_0__1_case_3;
  wire [4:0] unexpand_for_next_value_519_0__1_case_2_case_0;
  wire [4:0] unexpand_for_next_value_519_0__1_case_0;
  wire mp_rx;
  wire [159:0] t__metadata_payload_select__1;
  wire crp_rx;
  wire [4:0] unexpand_for_next_value_519_0__1_case_5;
  wire st4_5_case_cmp;
  wire st0_4_case_cmp;
  wire st4_3_case_cmp;
  wire ma_tx;
  wire [159:0] t__metadata_payload_select;
  wire st0_6_case_cmp;
  wire [63:0] mp_pld__1[2];
  wire [4:0] concat_2371;
  wire p0_all_active_inputs_valid;
  wire sa_tx;
  wire [31:0] length__1;
  wire [31:0] length;
  wire __t__metadata_addr_vld_buf;
  wire __t__metadata_addr_not_has_been_sent;
  wire t__metadata_addr_valid_inv;
  wire __t__streaming_addr_vld_buf;
  wire __t__streaming_addr_not_has_been_sent;
  wire t__streaming_addr_valid_inv;
  wire new_max_1_case_cmp;
  wire [31:0] new_read__2;
  wire __t__metadata_addr_valid_and_not_has_been_sent;
  wire t__metadata_addr_valid_load_en;
  wire __t__streaming_addr_valid_and_not_has_been_sent;
  wire t__streaming_addr_valid_load_en;
  wire new_state__4_1_case_cmp;
  wire new_state__6_1_case_cmp;
  wire t__metadata_addr_load_en;
  wire t__streaming_addr_load_en;
  wire nor_2345;
  wire nor_2346;
  wire nor_2347;
  wire and_2348;
  wire nor_2349;
  wire and_2350;
  wire nor_2351;
  wire and_2352;
  wire [1:0] ____state_4__next_value_predicates;
  wire [1:0] ____state_7__next_value_predicates;
  wire [1:0] ____state_8__next_value_predicates;
  wire [3:0] ____state_10__next_value_predicates;
  wire [9:0] ____state_0__next_value_predicates;
  wire p0_all_active_outputs_ready;
  wire [2:0] one_hot_2372;
  wire [2:0] one_hot_2373;
  wire [2:0] one_hot_2374;
  wire [4:0] one_hot_2375;
  wire [10:0] one_hot_2376;
  wire p0_stage_done;
  wire [30:0] add_2328;
  wire [3:0] concat_2357;
  wire t__metadata_payload_from_skid_rdy;
  wire and_2581;
  wire t__cur_row_partition_from_skid_rdy;
  wire and_2555;
  wire t__num_col_partitions_from_skid_rdy;
  wire t__tot_num_partitions_from_skid_rdy;
  wire [30:0] umul_2337;
  wire [31:0] new_read;
  wire [4:0] one_hot_2708;
  wire [5:0] one_hot_2714;
  wire and_2501;
  wire and_2502;
  wire and_2519;
  wire and_2526;
  wire and_2528;
  wire t__metadata_payload_data_valid_load_en;
  wire t__metadata_payload_to_is_not_rdy;
  wire t__cur_row_partition_data_valid_load_en;
  wire t__cur_row_partition_to_is_not_rdy;
  wire t__num_col_partitions_data_valid_load_en;
  wire t__tot_num_partitions_data_valid_load_en;
  wire [30:0] part_id__1;
  wire part_meta_idx__1_squeezed_portion_0_width_1;
  wire [31:0] payload_idx;
  wire ____state_4__at_most_one_next_value;
  wire ____state_7__at_most_one_next_value;
  wire ____state_8__at_most_one_next_value;
  wire ____state_10__at_most_one_next_value;
  wire ____state_0__at_most_one_next_value;
  wire [31:0] t__cur_row_partition_select__1;
  wire [31:0] t__num_col_partitions_select__1;
  wire [31:0] t__tot_num_partitions_select__1;
  wire [1:0] concat_2504;
  wire [31:0] new_current_col_part__1;
  wire [1:0] concat_2514;
  wire [1:0] concat_2521;
  wire [3:0] concat_2530;
  wire [31:0] new_state_counter__1;
  wire [9:0] concat_2548;
  wire __t__metadata_addr_valid_and_all_active_outputs_ready;
  wire __t__metadata_addr_valid_and_ready_txfr;
  wire __t__streaming_addr_valid_and_all_active_outputs_ready;
  wire __t__streaming_addr_valid_and_ready_txfr;
  wire t__metadata_payload_data_is_sent_to;
  wire t__metadata_payload_skid_data_load_en;
  wire t__metadata_payload_skid_valid_set_zero;
  wire t__cur_row_partition_data_is_sent_to;
  wire t__cur_row_partition_skid_data_load_en;
  wire t__cur_row_partition_skid_valid_set_zero;
  wire t__num_col_partitions_data_is_sent_to;
  wire t__num_col_partitions_skid_data_load_en;
  wire t__num_col_partitions_skid_valid_set_zero;
  wire t__tot_num_partitions_data_is_sent_to;
  wire t__tot_num_partitions_skid_data_load_en;
  wire t__tot_num_partitions_skid_valid_set_zero;
  wire [31:0] part_meta_idx__1;
  wire or_2721;
  wire or_2723;
  wire or_2725;
  wire or_2727;
  wire or_2729;
  wire [31:0] t__cur_row_partition_select;
  wire [31:0] t__num_col_partitions_select;
  wire [31:0] t__tot_num_partitions_select;
  wire [31:0] one_hot_sel_2505;
  wire and_2562;
  wire and_2564;
  wire [31:0] one_hot_sel_2515;
  wire and_2567;
  wire [31:0] one_hot_sel_2522;
  wire and_2570;
  wire [31:0] one_hot_sel_2531;
  wire and_2573;
  wire new_pred;
  wire and_2575;
  wire [4:0] one_hot_sel_2549;
  wire and_2578;
  wire __t__metadata_addr_not_stage_load;
  wire __t__metadata_addr_has_been_sent_reg_load_en;
  wire __t__streaming_addr_not_stage_load;
  wire __t__streaming_addr_has_been_sent_reg_load_en;
  wire t__metadata_payload_data_valid_load_en__1;
  wire t__metadata_payload_skid_valid_load_en;
  wire t__cur_row_partition_data_valid_load_en__1;
  wire t__cur_row_partition_skid_valid_load_en;
  wire t__num_col_partitions_data_valid_load_en__1;
  wire t__num_col_partitions_skid_valid_load_en;
  wire t__tot_num_partitions_data_valid_load_en__1;
  wire t__tot_num_partitions_skid_valid_load_en;
  wire [63:0] ma_pld__1;
  wire [63:0] sa_pld__4;
  wire or_2731;
  wire or_2733;
  assign unexpand_for_next_value_519_0__1_case_1 = 5'h0b;
  assign st7_2_case_cmp = ____state_0 == unexpand_for_next_value_519_0__1_case_1;
  assign eq_2299 = ____state_0 == 5'h15;
  assign unexpand_for_next_value_519_0__1_case_6_case_1 = 5'h00;
  assign unexpand_for_next_value_519_0__1_case_4_case_1 = 5'h1e;
  assign unexpand_for_next_value_519_0__1_case_3 = 5'h02;
  assign unexpand_for_next_value_519_0__1_case_2_case_0 = 5'h0c;
  assign unexpand_for_next_value_519_0__1_case_0 = 5'h0a;
  assign mp_rx = st7_2_case_cmp | eq_2299;
  assign t__metadata_payload_select__1 = __t__metadata_payload_valid_skid_reg ? __t__metadata_payload_skid_reg : __t__metadata_payload_reg;
  assign crp_rx = ____state_0 == unexpand_for_next_value_519_0__1_case_6_case_1;
  assign unexpand_for_next_value_519_0__1_case_5 = 5'h1f;
  assign st4_5_case_cmp = ____state_0 == unexpand_for_next_value_519_0__1_case_4_case_1;
  assign st0_4_case_cmp = ____state_0 == unexpand_for_next_value_519_0__1_case_3;
  assign st4_3_case_cmp = ____state_0 == unexpand_for_next_value_519_0__1_case_2_case_0;
  assign ma_tx = ____state_0 == unexpand_for_next_value_519_0__1_case_0;
  assign t__metadata_payload_select = mp_rx ? t__metadata_payload_select__1 : literal_2303;
  assign st0_6_case_cmp = ____state_0 == unexpand_for_next_value_519_0__1_case_5;
  assign mp_pld__1[0] = t__metadata_payload_select[95:32];
  assign mp_pld__1[1] = t__metadata_payload_select[159:96];
  assign concat_2371 = {st0_6_case_cmp, st4_5_case_cmp | ____state_0 == 5'h16, eq_2299, st0_4_case_cmp | st4_3_case_cmp, st7_2_case_cmp | ma_tx | crp_rx};
  assign p0_all_active_inputs_valid = (~mp_rx | __t__metadata_payload_valid_reg | __t__metadata_payload_valid_skid_reg) & (~crp_rx | __t__cur_row_partition_valid_reg | __t__cur_row_partition_valid_skid_reg) & (~crp_rx | __t__num_col_partitions_valid_reg | __t__num_col_partitions_valid_skid_reg) & (~crp_rx | __t__tot_num_partitions_valid_reg | __t__tot_num_partitions_valid_skid_reg);
  assign sa_tx = 1'h0 & concat_2371[0] | 1'h1 & concat_2371[1] | 1'h0 & concat_2371[2] | 1'h1 & concat_2371[3] | ____state_11 & concat_2371[4];
  assign length__1 = mp_pld__1[1'h1][63:32];
  assign length = mp_pld__1[1'h0][63:32];
  assign __t__metadata_addr_vld_buf = p0_all_active_inputs_valid & ma_tx;
  assign __t__metadata_addr_not_has_been_sent = ~__t__metadata_addr_has_been_sent_reg;
  assign t__metadata_addr_valid_inv = ~__t__metadata_addr_valid_reg;
  assign __t__streaming_addr_vld_buf = p0_all_active_inputs_valid & sa_tx;
  assign __t__streaming_addr_not_has_been_sent = ~__t__streaming_addr_has_been_sent_reg;
  assign t__streaming_addr_valid_inv = ~__t__streaming_addr_valid_reg;
  assign new_max_1_case_cmp = length__1 > length;
  assign new_read__2 = ____state_8 + 32'h0000_0001;
  assign __t__metadata_addr_valid_and_not_has_been_sent = __t__metadata_addr_vld_buf & __t__metadata_addr_not_has_been_sent;
  assign t__metadata_addr_valid_load_en = t__metadata_addr_rdy | t__metadata_addr_valid_inv;
  assign __t__streaming_addr_valid_and_not_has_been_sent = __t__streaming_addr_vld_buf & __t__streaming_addr_not_has_been_sent;
  assign t__streaming_addr_valid_load_en = t__streaming_addr_rdy | t__streaming_addr_valid_inv;
  assign new_state__4_1_case_cmp = ____state_10 == 32'h0000_0001;
  assign new_state__6_1_case_cmp = new_read__2 >= ____state_7;
  assign t__metadata_addr_load_en = __t__metadata_addr_valid_and_not_has_been_sent & t__metadata_addr_valid_load_en;
  assign t__streaming_addr_load_en = __t__streaming_addr_valid_and_not_has_been_sent & t__streaming_addr_valid_load_en;
  assign nor_2345 = ~(~st7_2_case_cmp | new_state__4_1_case_cmp | new_max_1_case_cmp);
  assign nor_2346 = ~(~st7_2_case_cmp | new_state__4_1_case_cmp | ~new_max_1_case_cmp);
  assign nor_2347 = ~(~st7_2_case_cmp | new_state__4_1_case_cmp);
  assign and_2348 = st7_2_case_cmp & new_state__4_1_case_cmp;
  assign nor_2349 = ~(~st0_4_case_cmp | new_state__6_1_case_cmp);
  assign and_2350 = st0_4_case_cmp & new_state__6_1_case_cmp;
  assign nor_2351 = ~(~st0_6_case_cmp | ____state_11);
  assign and_2352 = st0_6_case_cmp & ____state_11;
  assign ____state_4__next_value_predicates = {crp_rx, st4_5_case_cmp};
  assign ____state_7__next_value_predicates = {nor_2345, nor_2346};
  assign ____state_8__next_value_predicates = {st0_4_case_cmp, nor_2347};
  assign ____state_10__next_value_predicates = {crp_rx, ma_tx, nor_2347, and_2348};
  assign ____state_0__next_value_predicates = {crp_rx, ma_tx, st4_3_case_cmp, st4_5_case_cmp, nor_2347, and_2348, nor_2349, and_2350, nor_2351, and_2352};
  assign p0_all_active_outputs_ready = (~ma_tx | t__metadata_addr_load_en | __t__metadata_addr_has_been_sent_reg) & (~sa_tx | t__streaming_addr_load_en | __t__streaming_addr_has_been_sent_reg);
  assign one_hot_2372 = {____state_4__next_value_predicates[1:0] == 2'h0, ____state_4__next_value_predicates[1] && !____state_4__next_value_predicates[0], ____state_4__next_value_predicates[0]};
  assign one_hot_2373 = {____state_7__next_value_predicates[1:0] == 2'h0, ____state_7__next_value_predicates[1] && !____state_7__next_value_predicates[0], ____state_7__next_value_predicates[0]};
  assign one_hot_2374 = {____state_8__next_value_predicates[1:0] == 2'h0, ____state_8__next_value_predicates[1] && !____state_8__next_value_predicates[0], ____state_8__next_value_predicates[0]};
  assign one_hot_2375 = {____state_10__next_value_predicates[3:0] == 4'h0, ____state_10__next_value_predicates[3] && ____state_10__next_value_predicates[2:0] == 3'h0, ____state_10__next_value_predicates[2] && ____state_10__next_value_predicates[1:0] == 2'h0, ____state_10__next_value_predicates[1] && !____state_10__next_value_predicates[0], ____state_10__next_value_predicates[0]};
  assign one_hot_2376 = {____state_0__next_value_predicates[9:0] == 10'h000, ____state_0__next_value_predicates[9] && ____state_0__next_value_predicates[8:0] == 9'h000, ____state_0__next_value_predicates[8] && ____state_0__next_value_predicates[7:0] == 8'h00, ____state_0__next_value_predicates[7] && ____state_0__next_value_predicates[6:0] == 7'h00, ____state_0__next_value_predicates[6] && ____state_0__next_value_predicates[5:0] == 6'h00, ____state_0__next_value_predicates[5] && ____state_0__next_value_predicates[4:0] == 5'h00, ____state_0__next_value_predicates[4] && ____state_0__next_value_predicates[3:0] == 4'h0, ____state_0__next_value_predicates[3] && ____state_0__next_value_predicates[2:0] == 3'h0, ____state_0__next_value_predicates[2] && ____state_0__next_value_predicates[1:0] == 2'h0, ____state_0__next_value_predicates[1] && !____state_0__next_value_predicates[0], ____state_0__next_value_predicates[0]};
  assign p0_stage_done = p0_all_active_inputs_valid & p0_all_active_outputs_ready;
  assign add_2328 = ____state_3[30:0] + ____state_5[31:1];
  assign concat_2357 = {st0_6_case_cmp, st4_5_case_cmp, st0_4_case_cmp, st4_3_case_cmp};
  assign t__metadata_payload_from_skid_rdy = ~__t__metadata_payload_valid_skid_reg;
  assign and_2581 = p0_stage_done & mp_rx;
  assign t__cur_row_partition_from_skid_rdy = ~__t__cur_row_partition_valid_skid_reg;
  assign and_2555 = crp_rx & p0_stage_done;
  assign t__num_col_partitions_from_skid_rdy = ~__t__num_col_partitions_valid_skid_reg;
  assign t__tot_num_partitions_from_skid_rdy = ~__t__tot_num_partitions_valid_skid_reg;
  assign umul_2337 = umul31b_31b_x_31b(____state_1[30:0], ____state_2[30:0]);
  assign new_read = 32'h0000_0000;
  assign one_hot_2708 = {concat_2357[3:0] == 4'h0, concat_2357[3] && concat_2357[2:0] == 3'h0, concat_2357[2] && concat_2357[1:0] == 2'h0, concat_2357[1] && !concat_2357[0], concat_2357[0]};
  assign one_hot_2714 = {concat_2371[4:0] == 5'h00, concat_2371[4] && concat_2371[3:0] == 4'h0, concat_2371[3] && concat_2371[2:0] == 3'h0, concat_2371[2] && concat_2371[1:0] == 2'h0, concat_2371[1] && !concat_2371[0], concat_2371[0]};
  assign and_2501 = crp_rx & p0_stage_done;
  assign and_2502 = st4_5_case_cmp & p0_stage_done;
  assign and_2519 = nor_2347 & p0_stage_done;
  assign and_2526 = ma_tx & p0_stage_done;
  assign and_2528 = and_2348 & p0_stage_done;
  assign t__metadata_payload_data_valid_load_en = t__metadata_payload_vld & t__metadata_payload_from_skid_rdy;
  assign t__metadata_payload_to_is_not_rdy = ~and_2581;
  assign t__cur_row_partition_data_valid_load_en = t__cur_row_partition_vld & t__cur_row_partition_from_skid_rdy;
  assign t__cur_row_partition_to_is_not_rdy = ~and_2555;
  assign t__num_col_partitions_data_valid_load_en = t__num_col_partitions_vld & t__num_col_partitions_from_skid_rdy;
  assign t__tot_num_partitions_data_valid_load_en = t__tot_num_partitions_vld & t__tot_num_partitions_from_skid_rdy;
  assign part_id__1 = umul_2337 + ____state_4[30:0];
  assign part_meta_idx__1_squeezed_portion_0_width_1 = ____state_10 != new_read;
  assign payload_idx = {add_2328, ____state_5[0]} + ____state_8;
  assign ____state_4__at_most_one_next_value = crp_rx == one_hot_2372[1] & st4_5_case_cmp == one_hot_2372[0];
  assign ____state_7__at_most_one_next_value = nor_2345 == one_hot_2373[1] & nor_2346 == one_hot_2373[0];
  assign ____state_8__at_most_one_next_value = st0_4_case_cmp == one_hot_2374[1] & nor_2347 == one_hot_2374[0];
  assign ____state_10__at_most_one_next_value = crp_rx == one_hot_2375[3] & ma_tx == one_hot_2375[2] & nor_2347 == one_hot_2375[1] & and_2348 == one_hot_2375[0];
  assign ____state_0__at_most_one_next_value = crp_rx == one_hot_2376[9] & ma_tx == one_hot_2376[8] & st4_3_case_cmp == one_hot_2376[7] & st4_5_case_cmp == one_hot_2376[6] & nor_2347 == one_hot_2376[5] & and_2348 == one_hot_2376[4] & nor_2349 == one_hot_2376[3] & and_2350 == one_hot_2376[2] & nor_2351 == one_hot_2376[1] & and_2352 == one_hot_2376[0];
  assign t__cur_row_partition_select__1 = __t__cur_row_partition_valid_skid_reg ? __t__cur_row_partition_skid_reg : __t__cur_row_partition_reg;
  assign t__num_col_partitions_select__1 = __t__num_col_partitions_valid_skid_reg ? __t__num_col_partitions_skid_reg : __t__num_col_partitions_reg;
  assign t__tot_num_partitions_select__1 = __t__tot_num_partitions_valid_skid_reg ? __t__tot_num_partitions_skid_reg : __t__tot_num_partitions_reg;
  assign concat_2504 = {and_2501, and_2502};
  assign new_current_col_part__1 = ____state_4 + 32'h0000_0001;
  assign concat_2514 = {nor_2345 & p0_stage_done, nor_2346 & p0_stage_done};
  assign concat_2521 = {st0_4_case_cmp & p0_stage_done, and_2519};
  assign concat_2530 = {and_2501, and_2526, and_2519, and_2528};
  assign new_state_counter__1 = ____state_10 + 32'h0000_0001;
  assign concat_2548 = {and_2501, and_2526, st4_3_case_cmp & p0_stage_done, and_2502, and_2519, and_2528, nor_2349 & p0_stage_done, and_2350 & p0_stage_done, nor_2351 & p0_stage_done, and_2352 & p0_stage_done};
  assign __t__metadata_addr_valid_and_all_active_outputs_ready = __t__metadata_addr_vld_buf & p0_all_active_outputs_ready;
  assign __t__metadata_addr_valid_and_ready_txfr = __t__metadata_addr_valid_and_not_has_been_sent & t__metadata_addr_load_en;
  assign __t__streaming_addr_valid_and_all_active_outputs_ready = __t__streaming_addr_vld_buf & p0_all_active_outputs_ready;
  assign __t__streaming_addr_valid_and_ready_txfr = __t__streaming_addr_valid_and_not_has_been_sent & t__streaming_addr_load_en;
  assign t__metadata_payload_data_is_sent_to = __t__metadata_payload_valid_reg & and_2581 & t__metadata_payload_from_skid_rdy;
  assign t__metadata_payload_skid_data_load_en = __t__metadata_payload_valid_reg & t__metadata_payload_data_valid_load_en & t__metadata_payload_to_is_not_rdy;
  assign t__metadata_payload_skid_valid_set_zero = __t__metadata_payload_valid_skid_reg & and_2581;
  assign t__cur_row_partition_data_is_sent_to = __t__cur_row_partition_valid_reg & and_2555 & t__cur_row_partition_from_skid_rdy;
  assign t__cur_row_partition_skid_data_load_en = __t__cur_row_partition_valid_reg & t__cur_row_partition_data_valid_load_en & t__cur_row_partition_to_is_not_rdy;
  assign t__cur_row_partition_skid_valid_set_zero = __t__cur_row_partition_valid_skid_reg & and_2555;
  assign t__num_col_partitions_data_is_sent_to = __t__num_col_partitions_valid_reg & and_2555 & t__num_col_partitions_from_skid_rdy;
  assign t__num_col_partitions_skid_data_load_en = __t__num_col_partitions_valid_reg & t__num_col_partitions_data_valid_load_en & t__cur_row_partition_to_is_not_rdy;
  assign t__num_col_partitions_skid_valid_set_zero = __t__num_col_partitions_valid_skid_reg & and_2555;
  assign t__tot_num_partitions_data_is_sent_to = __t__tot_num_partitions_valid_reg & and_2555 & t__tot_num_partitions_from_skid_rdy;
  assign t__tot_num_partitions_skid_data_load_en = __t__tot_num_partitions_valid_reg & t__tot_num_partitions_data_valid_load_en & t__cur_row_partition_to_is_not_rdy;
  assign t__tot_num_partitions_skid_valid_set_zero = __t__tot_num_partitions_valid_skid_reg & and_2555;
  assign part_meta_idx__1 = {part_id__1, part_meta_idx__1_squeezed_portion_0_width_1};
  assign or_2721 = ~p0_stage_done | ____state_4__at_most_one_next_value | rst;
  assign or_2723 = ~p0_stage_done | ____state_7__at_most_one_next_value | rst;
  assign or_2725 = ~p0_stage_done | ____state_8__at_most_one_next_value | rst;
  assign or_2727 = ~p0_stage_done | ____state_10__at_most_one_next_value | rst;
  assign or_2729 = ~p0_stage_done | ____state_0__at_most_one_next_value | rst;
  assign t__cur_row_partition_select = crp_rx ? t__cur_row_partition_select__1 : 32'h0000_0000;
  assign t__num_col_partitions_select = crp_rx ? t__num_col_partitions_select__1 : 32'h0000_0000;
  assign t__tot_num_partitions_select = crp_rx ? t__tot_num_partitions_select__1 : 32'h0000_0000;
  assign one_hot_sel_2505 = new_current_col_part__1 & {32{concat_2504[0]}} | new_read & {32{concat_2504[1]}};
  assign and_2562 = (crp_rx | st4_5_case_cmp) & p0_stage_done;
  assign and_2564 = and_2348 & p0_stage_done;
  assign one_hot_sel_2515 = length__1 & {32{concat_2514[0]}} | length & {32{concat_2514[1]}};
  assign and_2567 = (nor_2345 | nor_2346) & p0_stage_done;
  assign one_hot_sel_2522 = new_read & {32{concat_2521[0]}} | new_read__2 & {32{concat_2521[1]}};
  assign and_2570 = (st0_4_case_cmp | nor_2347) & p0_stage_done;
  assign one_hot_sel_2531 = new_state_counter__1 & {32{concat_2530[0]}} | new_read & {32{concat_2530[1]}} | new_state_counter__1 & {32{concat_2530[2]}} | new_read & {32{concat_2530[3]}};
  assign and_2573 = (crp_rx | ma_tx | nor_2347 | and_2348) & p0_stage_done;
  assign new_pred = new_current_col_part__1 >= ____state_2;
  assign and_2575 = st4_5_case_cmp & p0_stage_done;
  assign one_hot_sel_2549 = unexpand_for_next_value_519_0__1_case_6_case_1 & {5{concat_2548[0]}} | unexpand_for_next_value_519_0__1_case_0 & {5{concat_2548[1]}} | unexpand_for_next_value_519_0__1_case_4_case_1 & {5{concat_2548[2]}} | unexpand_for_next_value_519_0__1_case_3 & {5{concat_2548[3]}} | unexpand_for_next_value_519_0__1_case_0 & {5{concat_2548[4]}} | unexpand_for_next_value_519_0__1_case_2_case_0 & {5{concat_2548[5]}} | unexpand_for_next_value_519_0__1_case_5 & {5{concat_2548[6]}} | unexpand_for_next_value_519_0__1_case_3 & {5{concat_2548[7]}} | unexpand_for_next_value_519_0__1_case_1 & {5{concat_2548[8]}} | unexpand_for_next_value_519_0__1_case_0 & {5{concat_2548[9]}};
  assign and_2578 = (crp_rx | ma_tx | st4_3_case_cmp | st4_5_case_cmp | nor_2347 | and_2348 | nor_2349 | and_2350 | nor_2351 | and_2352) & p0_stage_done;
  assign __t__metadata_addr_not_stage_load = ~__t__metadata_addr_valid_and_all_active_outputs_ready;
  assign __t__metadata_addr_has_been_sent_reg_load_en = __t__metadata_addr_valid_and_ready_txfr | __t__metadata_addr_valid_and_all_active_outputs_ready;
  assign __t__streaming_addr_not_stage_load = ~__t__streaming_addr_valid_and_all_active_outputs_ready;
  assign __t__streaming_addr_has_been_sent_reg_load_en = __t__streaming_addr_valid_and_ready_txfr | __t__streaming_addr_valid_and_all_active_outputs_ready;
  assign t__metadata_payload_data_valid_load_en__1 = t__metadata_payload_data_is_sent_to | t__metadata_payload_data_valid_load_en;
  assign t__metadata_payload_skid_valid_load_en = t__metadata_payload_skid_data_load_en | t__metadata_payload_skid_valid_set_zero;
  assign t__cur_row_partition_data_valid_load_en__1 = t__cur_row_partition_data_is_sent_to | t__cur_row_partition_data_valid_load_en;
  assign t__cur_row_partition_skid_valid_load_en = t__cur_row_partition_skid_data_load_en | t__cur_row_partition_skid_valid_set_zero;
  assign t__num_col_partitions_data_valid_load_en__1 = t__num_col_partitions_data_is_sent_to | t__num_col_partitions_data_valid_load_en;
  assign t__num_col_partitions_skid_valid_load_en = t__num_col_partitions_skid_data_load_en | t__num_col_partitions_skid_valid_set_zero;
  assign t__tot_num_partitions_data_valid_load_en__1 = t__tot_num_partitions_data_is_sent_to | t__tot_num_partitions_data_valid_load_en;
  assign t__tot_num_partitions_skid_valid_load_en = t__tot_num_partitions_skid_data_load_en | t__tot_num_partitions_skid_valid_set_zero;
  assign ma_pld__1 = {part_meta_idx__1, 2'h0, 30'h0000_0000};
  assign sa_pld__4 = {payload_idx & {32{st0_4_case_cmp}}, 2'h1 & {2{concat_2357[0]}} | 2'h0 & {2{concat_2357[1]}} | 2'h2 & {2{concat_2357[2]}} | 2'h3 & {2{concat_2357[3]}}, {29'h0000_0000, st0_6_case_cmp | st4_5_case_cmp | st0_4_case_cmp | st4_3_case_cmp}};
  assign or_2731 = ~p0_stage_done | concat_2357 == one_hot_2708[3:0] | rst;
  assign or_2733 = ~p0_stage_done | concat_2371 == one_hot_2714[4:0] | rst;
  always_ff @ (posedge clk) begin
    if (rst) begin
      ____state_0 <= 5'h00;
      ____state_3 <= 32'h0000_0000;
      ____state_5 <= 32'h0000_0000;
      ____state_8 <= 32'h0000_0000;
      ____state_1 <= 32'h0000_0000;
      ____state_2 <= 32'h0000_0000;
      ____state_10 <= 32'h0000_0000;
      ____state_7 <= 32'h0000_0000;
      ____state_4 <= 32'h0000_0000;
      ____state_11 <= 1'h0;
      __t__metadata_addr_has_been_sent_reg <= 1'h0;
      __t__streaming_addr_has_been_sent_reg <= 1'h0;
      __t__metadata_payload_reg <= __t__metadata_payload_reg_init;
      __t__metadata_payload_skid_reg <= __t__metadata_payload_skid_reg_init;
      __t__metadata_payload_valid_reg <= 1'h0;
      __t__metadata_payload_valid_skid_reg <= 1'h0;
      __t__cur_row_partition_reg <= 32'h0000_0000;
      __t__cur_row_partition_skid_reg <= 32'h0000_0000;
      __t__cur_row_partition_valid_reg <= 1'h0;
      __t__cur_row_partition_valid_skid_reg <= 1'h0;
      __t__num_col_partitions_reg <= 32'h0000_0000;
      __t__num_col_partitions_skid_reg <= 32'h0000_0000;
      __t__num_col_partitions_valid_reg <= 1'h0;
      __t__num_col_partitions_valid_skid_reg <= 1'h0;
      __t__tot_num_partitions_reg <= 32'h0000_0000;
      __t__tot_num_partitions_skid_reg <= 32'h0000_0000;
      __t__tot_num_partitions_valid_reg <= 1'h0;
      __t__tot_num_partitions_valid_skid_reg <= 1'h0;
      __t__metadata_addr_reg <= __t__metadata_addr_reg_init;
      __t__metadata_addr_valid_reg <= 1'h0;
      __t__streaming_addr_reg <= __t__streaming_addr_reg_init;
      __t__streaming_addr_valid_reg <= 1'h0;
    end else begin
      ____state_0 <= and_2578 ? one_hot_sel_2549 : ____state_0;
      ____state_3 <= and_2555 ? t__tot_num_partitions_select : ____state_3;
      ____state_5 <= and_2564 ? length : ____state_5;
      ____state_8 <= and_2570 ? one_hot_sel_2522 : ____state_8;
      ____state_1 <= and_2555 ? t__cur_row_partition_select : ____state_1;
      ____state_2 <= and_2555 ? t__num_col_partitions_select : ____state_2;
      ____state_10 <= and_2573 ? one_hot_sel_2531 : ____state_10;
      ____state_7 <= and_2567 ? one_hot_sel_2515 : ____state_7;
      ____state_4 <= and_2562 ? one_hot_sel_2505 : ____state_4;
      ____state_11 <= and_2575 ? new_pred : ____state_11;
      __t__metadata_addr_has_been_sent_reg <= __t__metadata_addr_has_been_sent_reg_load_en ? __t__metadata_addr_not_stage_load : __t__metadata_addr_has_been_sent_reg;
      __t__streaming_addr_has_been_sent_reg <= __t__streaming_addr_has_been_sent_reg_load_en ? __t__streaming_addr_not_stage_load : __t__streaming_addr_has_been_sent_reg;
      __t__metadata_payload_reg <= t__metadata_payload_data_valid_load_en ? t__metadata_payload : __t__metadata_payload_reg;
      __t__metadata_payload_skid_reg <= t__metadata_payload_skid_data_load_en ? __t__metadata_payload_reg : __t__metadata_payload_skid_reg;
      __t__metadata_payload_valid_reg <= t__metadata_payload_data_valid_load_en__1 ? t__metadata_payload_vld : __t__metadata_payload_valid_reg;
      __t__metadata_payload_valid_skid_reg <= t__metadata_payload_skid_valid_load_en ? t__metadata_payload_from_skid_rdy : __t__metadata_payload_valid_skid_reg;
      __t__cur_row_partition_reg <= t__cur_row_partition_data_valid_load_en ? t__cur_row_partition : __t__cur_row_partition_reg;
      __t__cur_row_partition_skid_reg <= t__cur_row_partition_skid_data_load_en ? __t__cur_row_partition_reg : __t__cur_row_partition_skid_reg;
      __t__cur_row_partition_valid_reg <= t__cur_row_partition_data_valid_load_en__1 ? t__cur_row_partition_vld : __t__cur_row_partition_valid_reg;
      __t__cur_row_partition_valid_skid_reg <= t__cur_row_partition_skid_valid_load_en ? t__cur_row_partition_from_skid_rdy : __t__cur_row_partition_valid_skid_reg;
      __t__num_col_partitions_reg <= t__num_col_partitions_data_valid_load_en ? t__num_col_partitions : __t__num_col_partitions_reg;
      __t__num_col_partitions_skid_reg <= t__num_col_partitions_skid_data_load_en ? __t__num_col_partitions_reg : __t__num_col_partitions_skid_reg;
      __t__num_col_partitions_valid_reg <= t__num_col_partitions_data_valid_load_en__1 ? t__num_col_partitions_vld : __t__num_col_partitions_valid_reg;
      __t__num_col_partitions_valid_skid_reg <= t__num_col_partitions_skid_valid_load_en ? t__num_col_partitions_from_skid_rdy : __t__num_col_partitions_valid_skid_reg;
      __t__tot_num_partitions_reg <= t__tot_num_partitions_data_valid_load_en ? t__tot_num_partitions : __t__tot_num_partitions_reg;
      __t__tot_num_partitions_skid_reg <= t__tot_num_partitions_skid_data_load_en ? __t__tot_num_partitions_reg : __t__tot_num_partitions_skid_reg;
      __t__tot_num_partitions_valid_reg <= t__tot_num_partitions_data_valid_load_en__1 ? t__tot_num_partitions_vld : __t__tot_num_partitions_valid_reg;
      __t__tot_num_partitions_valid_skid_reg <= t__tot_num_partitions_skid_valid_load_en ? t__tot_num_partitions_from_skid_rdy : __t__tot_num_partitions_valid_skid_reg;
      __t__metadata_addr_reg <= t__metadata_addr_load_en ? ma_pld__1 : __t__metadata_addr_reg;
      __t__metadata_addr_valid_reg <= t__metadata_addr_valid_load_en ? __t__metadata_addr_valid_and_not_has_been_sent : __t__metadata_addr_valid_reg;
      __t__streaming_addr_reg <= t__streaming_addr_load_en ? sa_pld__4 : __t__streaming_addr_reg;
      __t__streaming_addr_valid_reg <= t__streaming_addr_valid_load_en ? __t__streaming_addr_valid_and_not_has_been_sent : __t__streaming_addr_valid_reg;
    end
  end
  assign t__cur_row_partition_rdy = t__cur_row_partition_from_skid_rdy;
  assign t__metadata_addr = __t__metadata_addr_reg;
  assign t__metadata_addr_vld = __t__metadata_addr_valid_reg;
  assign t__metadata_payload_rdy = t__metadata_payload_from_skid_rdy;
  assign t__num_col_partitions_rdy = t__num_col_partitions_from_skid_rdy;
  assign t__streaming_addr = __t__streaming_addr_reg;
  assign t__streaming_addr_vld = __t__streaming_addr_valid_reg;
  assign t__tot_num_partitions_rdy = t__tot_num_partitions_from_skid_rdy;
  `ifdef ASSERT_ON
  ____state_4__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2721))) or_2721) else $fatal(0, "More than one next_value fired for state element: __state_4");
  ____state_7__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2723))) or_2723) else $fatal(0, "More than one next_value fired for state element: __state_7");
  ____state_8__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2725))) or_2725) else $fatal(0, "More than one next_value fired for state element: __state_8");
  ____state_10__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2727))) or_2727) else $fatal(0, "More than one next_value fired for state element: __state_10");
  ____state_0__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2729))) or_2729) else $fatal(0, "More than one next_value fired for state element: __state_0");
  __xls_invariant_priority_sel_2369_selector_one_hot_A: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2731))) or_2731) else $fatal(0, "Selector concat.2357 was expected to be one-hot, and is not.");
  __xls_invariant_sa_tx_selector_one_hot_A: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2733))) or_2733) else $fatal(0, "Selector concat.2371 was expected to be one-hot, and is not.");
  `endif  // ASSERT_ON
endmodule
`default_nettype wire
