module __t__shuffler_core_0_next(
  input wire clk,
  input wire rst,
  input wire [261:0] t__arbiter_combined_out,
  input wire t__arbiter_combined_out_vld,
  input wire t__arbiter_i_valid_rdy,
  input wire t__arbiter_payload_type_two_i_rdy,
  input wire t__arbiter_rotate_offset_rdy,
  input wire [95:0] t__multistream_payload_i__0,
  input wire t__multistream_payload_i__0_vld,
  input wire [95:0] t__multistream_payload_i__1,
  input wire t__multistream_payload_i__1_vld,
  input wire t__multistream_payload_o__0_rdy,
  input wire t__multistream_payload_o__1_rdy,
  output wire t__arbiter_combined_out_rdy,
  output wire [1:0] t__arbiter_i_valid,
  output wire t__arbiter_i_valid_vld,
  output wire [191:0] t__arbiter_payload_type_two_i,
  output wire t__arbiter_payload_type_two_i_vld,
  output wire [31:0] t__arbiter_rotate_offset,
  output wire t__arbiter_rotate_offset_vld,
  output wire t__multistream_payload_i__0_rdy,
  output wire t__multistream_payload_i__1_rdy,
  output wire [95:0] t__multistream_payload_o__0,
  output wire t__multistream_payload_o__0_vld,
  output wire [95:0] t__multistream_payload_o__1,
  output wire t__multistream_payload_o__1_vld
);
  wire [261:0] __t__arbiter_combined_out_reg_init = {{96'h0000_0000_0000_0000_0000_0000, 96'h0000_0000_0000_0000_0000_0000}, {1'h0, 1'h0}, {32'h0000_0000, 32'h0000_0000}, {1'h0, 1'h0}, {1'h0, 1'h0}};
  wire [261:0] __t__arbiter_combined_out_skid_reg_init = {{96'h0000_0000_0000_0000_0000_0000, 96'h0000_0000_0000_0000_0000_0000}, {1'h0, 1'h0}, {32'h0000_0000, 32'h0000_0000}, {1'h0, 1'h0}, {1'h0, 1'h0}};
  wire [95:0] __t__arbiter_payload_type_two_i_reg_init[2];
  assign __t__arbiter_payload_type_two_i_reg_init = '{96'h0000_0000_0000_0000_0000_0000, 96'h0000_0000_0000_0000_0000_0000};
  wire __t__arbiter_i_valid_reg_init[2];
  assign __t__arbiter_i_valid_reg_init = '{1'h0, 1'h0};
  wire [261:0] literal_1041 = {{96'h0000_0000_0000_0000_0000_0000, 96'h0000_0000_0000_0000_0000_0000}, {1'h0, 1'h0}, {32'h0000_0000, 32'h0000_0000}, {1'h0, 1'h0}, {1'h0, 1'h0}};
  reg ____state_1_0;
  reg ____state_1_1;
  reg [3:0] ____state_2;
  reg ____state_5;
  reg ____state_3;
  reg p0_valid;
  reg p1_valid;
  reg __t__multistream_payload_o__0_has_been_sent_reg;
  reg __t__arbiter_payload_type_two_i_has_been_sent_reg;
  reg __t__arbiter_i_valid_has_been_sent_reg;
  reg __t__arbiter_rotate_offset_has_been_sent_reg;
  reg __t__multistream_payload_o__1_has_been_sent_reg;
  reg [261:0] __t__arbiter_combined_out_reg;
  reg [261:0] __t__arbiter_combined_out_skid_reg;
  reg __t__arbiter_combined_out_valid_reg;
  reg __t__arbiter_combined_out_valid_skid_reg;
  reg [95:0] __t__multistream_payload_i__0_reg;
  reg [95:0] __t__multistream_payload_i__0_skid_reg;
  reg __t__multistream_payload_i__0_valid_reg;
  reg __t__multistream_payload_i__0_valid_skid_reg;
  reg [95:0] __t__multistream_payload_i__1_reg;
  reg [95:0] __t__multistream_payload_i__1_skid_reg;
  reg __t__multistream_payload_i__1_valid_reg;
  reg __t__multistream_payload_i__1_valid_skid_reg;
  reg [95:0] __t__multistream_payload_o__0_reg;
  reg __t__multistream_payload_o__0_valid_reg;
  reg [95:0] __t__arbiter_payload_type_two_i_reg[2];
  reg __t__arbiter_payload_type_two_i_valid_reg;
  reg __t__arbiter_i_valid_reg[2];
  reg __t__arbiter_i_valid_valid_reg;
  reg [31:0] __t__arbiter_rotate_offset_reg;
  reg __t__arbiter_rotate_offset_valid_reg;
  reg [95:0] __t__multistream_payload_o__1_reg;
  reg __t__multistream_payload_o__1_valid_reg;
  wire t__arbiter_combined_out_valid_or;
  wire [261:0] t__arbiter_combined_out_select__1;
  wire [261:0] t__arbiter_combined_out_select;
  wire arpv_pld[2];
  wire array_index_1046;
  wire read_input_predicate;
  wire t__multistream_payload_i__0_valid_or;
  wire array_index_1055;
  wire t__multistream_payload_o__0_valid_inv;
  wire t__arbiter_payload_type_two_i_valid_inv;
  wire t__arbiter_i_valid_valid_inv;
  wire t__arbiter_rotate_offset_valid_inv;
  wire t__multistream_payload_o__1_valid_inv;
  wire [95:0] t__multistream_payload_i__0_select__1;
  wire read_input_predicate__1;
  wire t__multistream_payload_i__1_valid_or;
  wire eq_1089;
  wire __t__multistream_payload_o__0_not_has_been_sent;
  wire t__multistream_payload_o__0_valid_load_en;
  wire __t__arbiter_payload_type_two_i_not_has_been_sent;
  wire t__arbiter_payload_type_two_i_valid_load_en;
  wire __t__arbiter_i_valid_not_has_been_sent;
  wire t__arbiter_i_valid_valid_load_en;
  wire __t__arbiter_rotate_offset_not_has_been_sent;
  wire t__arbiter_rotate_offset_valid_load_en;
  wire __t__multistream_payload_o__1_not_has_been_sent;
  wire t__multistream_payload_o__1_valid_load_en;
  wire [31:0] axs_pld[2];
  wire [95:0] t__multistream_payload_i__0_select;
  wire [95:0] t__multistream_payload_i__1_select__1;
  wire nor_1098;
  wire send_eod_predicate;
  wire t__multistream_payload_o__0_load_en;
  wire t__arbiter_payload_type_two_i_load_en;
  wire t__arbiter_i_valid_load_en;
  wire t__arbiter_rotate_offset_load_en;
  wire t__multistream_payload_o__1_load_en;
  wire axv_pld[2];
  wire aoiv_pld[2];
  wire [31:0] array_index_1068;
  wire [95:0] t__multistream_payload_i__1_select;
  wire [31:0] array_index_1073;
  wire [1:0] ____state_2__next_value_predicates;
  wire __t__multistream_payload_o__0_has_sent_or_is_ready;
  wire __t__arbiter_payload_type_two_i_has_sent_or_is_ready;
  wire __t__arbiter_i_valid_has_sent_or_is_ready;
  wire __t__arbiter_rotate_offset_has_sent_or_is_ready;
  wire __t__multistream_payload_o__1_has_sent_or_is_ready;
  wire eq_1074;
  wire [2:0] one_hot_1119;
  wire p0_all_active_outputs_ready;
  wire [95:0] arptt_pld[2];
  wire t__arbiter_combined_out_from_skid_rdy;
  wire t__multistream_payload_i__0_from_skid_rdy;
  wire and_1202;
  wire t__multistream_payload_i__1_from_skid_rdy;
  wire and_1203;
  wire eq_1126;
  wire eq_1127;
  wire and_1189;
  wire and_1190;
  wire t__arbiter_combined_out_data_valid_load_en;
  wire t__arbiter_combined_out_to_is_not_rdy;
  wire t__multistream_payload_i__0_data_valid_load_en;
  wire t__multistream_payload_i__0_to_is_not_rdy;
  wire t__multistream_payload_i__1_data_valid_load_en;
  wire t__multistream_payload_i__1_to_is_not_rdy;
  wire and_1094;
  wire ____state_2__at_most_one_next_value;
  wire [1:0] concat_1192;
  wire [3:0] unexpand_for_next_value_299_2__1_case_1_case_1;
  wire [3:0] unexpand_for_next_value_299_2__1_case_1_case_0;
  wire __t__multistream_payload_o__0_valid_and_ready_txfr;
  wire __t__arbiter_payload_type_two_i_valid_and_ready_txfr;
  wire __t__arbiter_i_valid_valid_and_ready_txfr;
  wire __t__arbiter_rotate_offset_valid_and_ready_txfr;
  wire __t__multistream_payload_o__1_valid_and_ready_txfr;
  wire t__arbiter_combined_out_data_is_sent_to;
  wire t__arbiter_combined_out_skid_data_load_en;
  wire t__arbiter_combined_out_skid_valid_set_zero;
  wire t__multistream_payload_i__0_data_is_sent_to;
  wire t__multistream_payload_i__0_skid_data_load_en;
  wire t__multistream_payload_i__0_skid_valid_set_zero;
  wire t__multistream_payload_i__1_data_is_sent_to;
  wire t__multistream_payload_i__1_skid_data_load_en;
  wire t__multistream_payload_i__1_skid_valid_set_zero;
  wire [95:0] sel_1108;
  wire [95:0] p;
  wire [95:0] p__1;
  wire [30:0] leading_bits___state_3;
  wire [95:0] sel_1118;
  wire or_1382;
  wire p1_enable;
  wire p0_enable;
  wire new_sent_eod;
  wire or_1142;
  wire or_1143;
  wire [3:0] one_hot_sel_1193;
  wire or_1194;
  wire unexpand_for_next_value_299_3__1;
  wire __t__arbiter_i_valid_not_stage_load;
  wire __t__multistream_payload_o__0_has_been_sent_reg_load_en;
  wire __t__arbiter_payload_type_two_i_has_been_sent_reg_load_en;
  wire __t__arbiter_i_valid_has_been_sent_reg_load_en;
  wire __t__arbiter_rotate_offset_has_been_sent_reg_load_en;
  wire __t__multistream_payload_o__1_has_been_sent_reg_load_en;
  wire t__arbiter_combined_out_data_valid_load_en__1;
  wire t__arbiter_combined_out_skid_valid_load_en;
  wire t__multistream_payload_i__0_data_valid_load_en__1;
  wire t__multistream_payload_i__0_skid_valid_load_en;
  wire t__multistream_payload_i__1_data_valid_load_en__1;
  wire t__multistream_payload_i__1_skid_valid_load_en;
  wire [95:0] pld;
  wire [95:0] arb_payload_in[2];
  wire arb_payload_valid[2];
  wire [31:0] extended___state_3;
  wire [95:0] pld__1;
  assign t__arbiter_combined_out_valid_or = __t__arbiter_combined_out_valid_reg | __t__arbiter_combined_out_valid_skid_reg;
  assign t__arbiter_combined_out_select__1 = __t__arbiter_combined_out_valid_skid_reg ? __t__arbiter_combined_out_skid_reg : __t__arbiter_combined_out_reg;
  assign t__arbiter_combined_out_select = t__arbiter_combined_out_valid_or ? t__arbiter_combined_out_select__1 : literal_1041;
  assign arpv_pld[0] = t__arbiter_combined_out_select[68:68];
  assign arpv_pld[1] = t__arbiter_combined_out_select[69:69];
  assign array_index_1046 = arpv_pld[1'h0];
  assign read_input_predicate = ~(array_index_1046 | ____state_1_0);
  assign t__multistream_payload_i__0_valid_or = __t__multistream_payload_i__0_valid_reg | __t__multistream_payload_i__0_valid_skid_reg;
  assign array_index_1055 = arpv_pld[1'h1];
  assign t__multistream_payload_o__0_valid_inv = ~__t__multistream_payload_o__0_valid_reg;
  assign t__arbiter_payload_type_two_i_valid_inv = ~__t__arbiter_payload_type_two_i_valid_reg;
  assign t__arbiter_i_valid_valid_inv = ~__t__arbiter_i_valid_valid_reg;
  assign t__arbiter_rotate_offset_valid_inv = ~__t__arbiter_rotate_offset_valid_reg;
  assign t__multistream_payload_o__1_valid_inv = ~__t__multistream_payload_o__1_valid_reg;
  assign t__multistream_payload_i__0_select__1 = __t__multistream_payload_i__0_valid_skid_reg ? __t__multistream_payload_i__0_skid_reg : __t__multistream_payload_i__0_reg;
  assign read_input_predicate__1 = ~(array_index_1055 | ____state_1_1);
  assign t__multistream_payload_i__1_valid_or = __t__multistream_payload_i__1_valid_reg | __t__multistream_payload_i__1_valid_skid_reg;
  assign eq_1089 = ____state_2 == 4'h0;
  assign __t__multistream_payload_o__0_not_has_been_sent = ~__t__multistream_payload_o__0_has_been_sent_reg;
  assign t__multistream_payload_o__0_valid_load_en = t__multistream_payload_o__0_rdy | t__multistream_payload_o__0_valid_inv;
  assign __t__arbiter_payload_type_two_i_not_has_been_sent = ~__t__arbiter_payload_type_two_i_has_been_sent_reg;
  assign t__arbiter_payload_type_two_i_valid_load_en = t__arbiter_payload_type_two_i_rdy | t__arbiter_payload_type_two_i_valid_inv;
  assign __t__arbiter_i_valid_not_has_been_sent = ~__t__arbiter_i_valid_has_been_sent_reg;
  assign t__arbiter_i_valid_valid_load_en = t__arbiter_i_valid_rdy | t__arbiter_i_valid_valid_inv;
  assign __t__arbiter_rotate_offset_not_has_been_sent = ~__t__arbiter_rotate_offset_has_been_sent_reg;
  assign t__arbiter_rotate_offset_valid_load_en = t__arbiter_rotate_offset_rdy | t__arbiter_rotate_offset_valid_inv;
  assign __t__multistream_payload_o__1_not_has_been_sent = ~__t__multistream_payload_o__1_has_been_sent_reg;
  assign t__multistream_payload_o__1_valid_load_en = t__multistream_payload_o__1_rdy | t__multistream_payload_o__1_valid_inv;
  assign axs_pld[0] = t__arbiter_combined_out_select[35:4];
  assign axs_pld[1] = t__arbiter_combined_out_select[67:36];
  assign t__multistream_payload_i__0_select = read_input_predicate & t__multistream_payload_i__0_valid_or ? t__multistream_payload_i__0_select__1 : 96'h0000_0000_0000_0000_0000_0000;
  assign t__multistream_payload_i__1_select__1 = __t__multistream_payload_i__1_valid_skid_reg ? __t__multistream_payload_i__1_skid_reg : __t__multistream_payload_i__1_reg;
  assign nor_1098 = ~(~____state_1_0 | ~____state_1_1 | eq_1089);
  assign send_eod_predicate = ____state_1_0 & ____state_1_1 & eq_1089;
  assign t__multistream_payload_o__0_load_en = __t__multistream_payload_o__0_not_has_been_sent & t__multistream_payload_o__0_valid_load_en;
  assign t__arbiter_payload_type_two_i_load_en = __t__arbiter_payload_type_two_i_not_has_been_sent & t__arbiter_payload_type_two_i_valid_load_en;
  assign t__arbiter_i_valid_load_en = __t__arbiter_i_valid_not_has_been_sent & t__arbiter_i_valid_valid_load_en;
  assign t__arbiter_rotate_offset_load_en = __t__arbiter_rotate_offset_not_has_been_sent & t__arbiter_rotate_offset_valid_load_en;
  assign t__multistream_payload_o__1_load_en = __t__multistream_payload_o__1_not_has_been_sent & t__multistream_payload_o__1_valid_load_en;
  assign axv_pld[0] = t__arbiter_combined_out_select[2:2];
  assign axv_pld[1] = t__arbiter_combined_out_select[3:3];
  assign aoiv_pld[0] = t__arbiter_combined_out_select[0:0];
  assign aoiv_pld[1] = t__arbiter_combined_out_select[1:1];
  assign array_index_1068 = axs_pld[1'h0];
  assign t__multistream_payload_i__1_select = read_input_predicate__1 & t__multistream_payload_i__1_valid_or ? t__multistream_payload_i__1_select__1 : 96'h0000_0000_0000_0000_0000_0000;
  assign array_index_1073 = axs_pld[1'h1];
  assign ____state_2__next_value_predicates = {nor_1098, send_eod_predicate};
  assign __t__multistream_payload_o__0_has_sent_or_is_ready = t__multistream_payload_o__0_load_en | __t__multistream_payload_o__0_has_been_sent_reg;
  assign __t__arbiter_payload_type_two_i_has_sent_or_is_ready = t__arbiter_payload_type_two_i_load_en | __t__arbiter_payload_type_two_i_has_been_sent_reg;
  assign __t__arbiter_i_valid_has_sent_or_is_ready = t__arbiter_i_valid_load_en | __t__arbiter_i_valid_has_been_sent_reg;
  assign __t__arbiter_rotate_offset_has_sent_or_is_ready = t__arbiter_rotate_offset_load_en | __t__arbiter_rotate_offset_has_been_sent_reg;
  assign __t__multistream_payload_o__1_has_sent_or_is_ready = t__multistream_payload_o__1_load_en | __t__multistream_payload_o__1_has_been_sent_reg;
  assign eq_1074 = t__multistream_payload_i__0_select[95:94] == 2'h3;
  assign one_hot_1119 = {____state_2__next_value_predicates[1:0] == 2'h0, ____state_2__next_value_predicates[1] && !____state_2__next_value_predicates[0], ____state_2__next_value_predicates[0]};
  assign p0_all_active_outputs_ready = __t__multistream_payload_o__0_has_sent_or_is_ready & __t__arbiter_payload_type_two_i_has_sent_or_is_ready & __t__arbiter_i_valid_has_sent_or_is_ready & __t__arbiter_rotate_offset_has_sent_or_is_ready & __t__multistream_payload_o__1_has_sent_or_is_ready;
  assign arptt_pld[0] = t__arbiter_combined_out_select[165:70];
  assign arptt_pld[1] = t__arbiter_combined_out_select[261:166];
  assign t__arbiter_combined_out_from_skid_rdy = ~__t__arbiter_combined_out_valid_skid_reg;
  assign t__multistream_payload_i__0_from_skid_rdy = ~__t__multistream_payload_i__0_valid_skid_reg;
  assign and_1202 = p0_all_active_outputs_ready & read_input_predicate;
  assign t__multistream_payload_i__1_from_skid_rdy = ~__t__multistream_payload_i__1_valid_skid_reg;
  assign and_1203 = p0_all_active_outputs_ready & read_input_predicate__1;
  assign eq_1126 = t__multistream_payload_i__0_select[95:94] == 2'h2;
  assign eq_1127 = t__multistream_payload_i__1_select[95:94] == 2'h2;
  assign and_1189 = nor_1098 & p0_all_active_outputs_ready;
  assign and_1190 = send_eod_predicate & p0_all_active_outputs_ready;
  assign t__arbiter_combined_out_data_valid_load_en = t__arbiter_combined_out_vld & t__arbiter_combined_out_from_skid_rdy;
  assign t__arbiter_combined_out_to_is_not_rdy = ~p0_all_active_outputs_ready;
  assign t__multistream_payload_i__0_data_valid_load_en = t__multistream_payload_i__0_vld & t__multistream_payload_i__0_from_skid_rdy;
  assign t__multistream_payload_i__0_to_is_not_rdy = ~and_1202;
  assign t__multistream_payload_i__1_data_valid_load_en = t__multistream_payload_i__1_vld & t__multistream_payload_i__1_from_skid_rdy;
  assign t__multistream_payload_i__1_to_is_not_rdy = ~and_1203;
  assign and_1094 = ____state_5 & eq_1074;
  assign ____state_2__at_most_one_next_value = nor_1098 == one_hot_1119[1] & send_eod_predicate == one_hot_1119[0];
  assign concat_1192 = {and_1189, and_1190};
  assign unexpand_for_next_value_299_2__1_case_1_case_1 = 4'ha;
  assign unexpand_for_next_value_299_2__1_case_1_case_0 = ____state_2 + 4'hf;
  assign __t__multistream_payload_o__0_valid_and_ready_txfr = __t__multistream_payload_o__0_not_has_been_sent & t__multistream_payload_o__0_load_en;
  assign __t__arbiter_payload_type_two_i_valid_and_ready_txfr = __t__arbiter_payload_type_two_i_not_has_been_sent & t__arbiter_payload_type_two_i_load_en;
  assign __t__arbiter_i_valid_valid_and_ready_txfr = __t__arbiter_i_valid_not_has_been_sent & t__arbiter_i_valid_load_en;
  assign __t__arbiter_rotate_offset_valid_and_ready_txfr = __t__arbiter_rotate_offset_not_has_been_sent & t__arbiter_rotate_offset_load_en;
  assign __t__multistream_payload_o__1_valid_and_ready_txfr = __t__multistream_payload_o__1_not_has_been_sent & t__multistream_payload_o__1_load_en;
  assign t__arbiter_combined_out_data_is_sent_to = __t__arbiter_combined_out_valid_reg & p0_all_active_outputs_ready & t__arbiter_combined_out_from_skid_rdy;
  assign t__arbiter_combined_out_skid_data_load_en = __t__arbiter_combined_out_valid_reg & t__arbiter_combined_out_data_valid_load_en & t__arbiter_combined_out_to_is_not_rdy;
  assign t__arbiter_combined_out_skid_valid_set_zero = __t__arbiter_combined_out_valid_skid_reg & p0_all_active_outputs_ready;
  assign t__multistream_payload_i__0_data_is_sent_to = __t__multistream_payload_i__0_valid_reg & and_1202 & t__multistream_payload_i__0_from_skid_rdy;
  assign t__multistream_payload_i__0_skid_data_load_en = __t__multistream_payload_i__0_valid_reg & t__multistream_payload_i__0_data_valid_load_en & t__multistream_payload_i__0_to_is_not_rdy;
  assign t__multistream_payload_i__0_skid_valid_set_zero = __t__multistream_payload_i__0_valid_skid_reg & and_1202;
  assign t__multistream_payload_i__1_data_is_sent_to = __t__multistream_payload_i__1_valid_reg & and_1203 & t__multistream_payload_i__1_from_skid_rdy;
  assign t__multistream_payload_i__1_skid_data_load_en = __t__multistream_payload_i__1_valid_reg & t__multistream_payload_i__1_data_valid_load_en & t__multistream_payload_i__1_to_is_not_rdy;
  assign t__multistream_payload_i__1_skid_valid_set_zero = __t__multistream_payload_i__1_valid_skid_reg & and_1203;
  assign sel_1108 = and_1094 ? 96'hc000_0000_0000_0000_0000_0000 : arptt_pld[array_index_1068 > 32'h0000_0001 ? 1'h1 : array_index_1068[0:0]] & {96{axv_pld[1'h0] & aoiv_pld[array_index_1068 > 32'h0000_0001 ? 1'h1 : array_index_1068[0:0]]}};
  assign p = array_index_1046 ? arptt_pld[1'h0] : t__multistream_payload_i__0_select & {96{~eq_1074}};
  assign p__1 = array_index_1055 ? arptt_pld[1'h1] : t__multistream_payload_i__1_select & {96{t__multistream_payload_i__1_select[95:94] != 2'h3}};
  assign leading_bits___state_3 = 31'h0000_0000;
  assign sel_1118 = and_1094 ? 96'hc000_0000_0000_0000_0000_0000 : arptt_pld[array_index_1073 > 32'h0000_0001 ? 1'h1 : array_index_1073[0:0]] & {96{axv_pld[1'h1] & aoiv_pld[array_index_1073 > 32'h0000_0001 ? 1'h1 : array_index_1073[0:0]]}};
  assign or_1382 = ~p0_all_active_outputs_ready | ____state_2__at_most_one_next_value | rst;
  assign p1_enable = 1'h1;
  assign p0_enable = 1'h1;
  assign new_sent_eod = send_eod_predicate & ~____state_5 | ~(eq_1074 | ~____state_5);
  assign or_1142 = eq_1126 | ~(eq_1126 | eq_1089 | ~____state_1_0);
  assign or_1143 = eq_1127 | ~(eq_1127 | eq_1089 | ~____state_1_1);
  assign one_hot_sel_1193 = unexpand_for_next_value_299_2__1_case_1_case_1 & {4{concat_1192[0]}} | unexpand_for_next_value_299_2__1_case_1_case_0 & {4{concat_1192[1]}};
  assign or_1194 = and_1189 | and_1190;
  assign unexpand_for_next_value_299_3__1 = ~____state_3;
  assign __t__arbiter_i_valid_not_stage_load = ~p0_all_active_outputs_ready;
  assign __t__multistream_payload_o__0_has_been_sent_reg_load_en = __t__multistream_payload_o__0_valid_and_ready_txfr | p0_all_active_outputs_ready;
  assign __t__arbiter_payload_type_two_i_has_been_sent_reg_load_en = __t__arbiter_payload_type_two_i_valid_and_ready_txfr | p0_all_active_outputs_ready;
  assign __t__arbiter_i_valid_has_been_sent_reg_load_en = __t__arbiter_i_valid_valid_and_ready_txfr | p0_all_active_outputs_ready;
  assign __t__arbiter_rotate_offset_has_been_sent_reg_load_en = __t__arbiter_rotate_offset_valid_and_ready_txfr | p0_all_active_outputs_ready;
  assign __t__multistream_payload_o__1_has_been_sent_reg_load_en = __t__multistream_payload_o__1_valid_and_ready_txfr | p0_all_active_outputs_ready;
  assign t__arbiter_combined_out_data_valid_load_en__1 = t__arbiter_combined_out_data_is_sent_to | t__arbiter_combined_out_data_valid_load_en;
  assign t__arbiter_combined_out_skid_valid_load_en = t__arbiter_combined_out_skid_data_load_en | t__arbiter_combined_out_skid_valid_set_zero;
  assign t__multistream_payload_i__0_data_valid_load_en__1 = t__multistream_payload_i__0_data_is_sent_to | t__multistream_payload_i__0_data_valid_load_en;
  assign t__multistream_payload_i__0_skid_valid_load_en = t__multistream_payload_i__0_skid_data_load_en | t__multistream_payload_i__0_skid_valid_set_zero;
  assign t__multistream_payload_i__1_data_valid_load_en__1 = t__multistream_payload_i__1_data_is_sent_to | t__multistream_payload_i__1_data_valid_load_en;
  assign t__multistream_payload_i__1_skid_valid_load_en = t__multistream_payload_i__1_skid_data_load_en | t__multistream_payload_i__1_skid_valid_set_zero;
  assign pld = send_eod_predicate ? 96'h8000_0000_0000_0000_0000_0000 : sel_1108;
  assign arb_payload_in[0] = p;
  assign arb_payload_in[1] = p__1;
  assign arb_payload_valid[0] = ~(~array_index_1046 & t__multistream_payload_i__0_select[31:0] == 32'h0000_0000);
  assign arb_payload_valid[1] = ~(~array_index_1055 & t__multistream_payload_i__1_select[31:0] == 32'h0000_0000);
  assign extended___state_3 = {leading_bits___state_3, ____state_3};
  assign pld__1 = send_eod_predicate ? 96'h8000_0000_0000_0000_0000_0000 : sel_1118;
  always_ff @ (posedge clk) begin
    if (rst) begin
      ____state_1_0 <= 1'h0;
      ____state_1_1 <= 1'h0;
      ____state_2 <= 4'ha;
      ____state_5 <= 1'h0;
      ____state_3 <= 1'h0;
      p0_valid <= 1'h0;
      p1_valid <= 1'h0;
      __t__multistream_payload_o__0_has_been_sent_reg <= 1'h0;
      __t__arbiter_payload_type_two_i_has_been_sent_reg <= 1'h0;
      __t__arbiter_i_valid_has_been_sent_reg <= 1'h0;
      __t__arbiter_rotate_offset_has_been_sent_reg <= 1'h0;
      __t__multistream_payload_o__1_has_been_sent_reg <= 1'h0;
      __t__arbiter_combined_out_reg <= __t__arbiter_combined_out_reg_init;
      __t__arbiter_combined_out_skid_reg <= __t__arbiter_combined_out_skid_reg_init;
      __t__arbiter_combined_out_valid_reg <= 1'h0;
      __t__arbiter_combined_out_valid_skid_reg <= 1'h0;
      __t__multistream_payload_i__0_reg <= 96'h0000_0000_0000_0000_0000_0000;
      __t__multistream_payload_i__0_skid_reg <= 96'h0000_0000_0000_0000_0000_0000;
      __t__multistream_payload_i__0_valid_reg <= 1'h0;
      __t__multistream_payload_i__0_valid_skid_reg <= 1'h0;
      __t__multistream_payload_i__1_reg <= 96'h0000_0000_0000_0000_0000_0000;
      __t__multistream_payload_i__1_skid_reg <= 96'h0000_0000_0000_0000_0000_0000;
      __t__multistream_payload_i__1_valid_reg <= 1'h0;
      __t__multistream_payload_i__1_valid_skid_reg <= 1'h0;
      __t__multistream_payload_o__0_reg <= 96'h0000_0000_0000_0000_0000_0000;
      __t__multistream_payload_o__0_valid_reg <= 1'h0;
      __t__arbiter_payload_type_two_i_reg <= __t__arbiter_payload_type_two_i_reg_init;
      __t__arbiter_payload_type_two_i_valid_reg <= 1'h0;
      __t__arbiter_i_valid_reg <= __t__arbiter_i_valid_reg_init;
      __t__arbiter_i_valid_valid_reg <= 1'h0;
      __t__arbiter_rotate_offset_reg <= 32'h0000_0000;
      __t__arbiter_rotate_offset_valid_reg <= 1'h0;
      __t__multistream_payload_o__1_reg <= 96'h0000_0000_0000_0000_0000_0000;
      __t__multistream_payload_o__1_valid_reg <= 1'h0;
    end else begin
      ____state_1_0 <= p0_all_active_outputs_ready ? or_1142 : ____state_1_0;
      ____state_1_1 <= p0_all_active_outputs_ready ? or_1143 : ____state_1_1;
      ____state_2 <= or_1194 ? one_hot_sel_1193 : ____state_2;
      ____state_5 <= p0_all_active_outputs_ready ? new_sent_eod : ____state_5;
      ____state_3 <= p0_all_active_outputs_ready ? unexpand_for_next_value_299_3__1 : ____state_3;
      p0_valid <= p0_enable ? p0_all_active_outputs_ready : p0_valid;
      p1_valid <= p1_enable ? p0_valid : p1_valid;
      __t__multistream_payload_o__0_has_been_sent_reg <= __t__multistream_payload_o__0_has_been_sent_reg_load_en ? __t__arbiter_i_valid_not_stage_load : __t__multistream_payload_o__0_has_been_sent_reg;
      __t__arbiter_payload_type_two_i_has_been_sent_reg <= __t__arbiter_payload_type_two_i_has_been_sent_reg_load_en ? __t__arbiter_i_valid_not_stage_load : __t__arbiter_payload_type_two_i_has_been_sent_reg;
      __t__arbiter_i_valid_has_been_sent_reg <= __t__arbiter_i_valid_has_been_sent_reg_load_en ? __t__arbiter_i_valid_not_stage_load : __t__arbiter_i_valid_has_been_sent_reg;
      __t__arbiter_rotate_offset_has_been_sent_reg <= __t__arbiter_rotate_offset_has_been_sent_reg_load_en ? __t__arbiter_i_valid_not_stage_load : __t__arbiter_rotate_offset_has_been_sent_reg;
      __t__multistream_payload_o__1_has_been_sent_reg <= __t__multistream_payload_o__1_has_been_sent_reg_load_en ? __t__arbiter_i_valid_not_stage_load : __t__multistream_payload_o__1_has_been_sent_reg;
      __t__arbiter_combined_out_reg <= t__arbiter_combined_out_data_valid_load_en ? t__arbiter_combined_out : __t__arbiter_combined_out_reg;
      __t__arbiter_combined_out_skid_reg <= t__arbiter_combined_out_skid_data_load_en ? __t__arbiter_combined_out_reg : __t__arbiter_combined_out_skid_reg;
      __t__arbiter_combined_out_valid_reg <= t__arbiter_combined_out_data_valid_load_en__1 ? t__arbiter_combined_out_vld : __t__arbiter_combined_out_valid_reg;
      __t__arbiter_combined_out_valid_skid_reg <= t__arbiter_combined_out_skid_valid_load_en ? t__arbiter_combined_out_from_skid_rdy : __t__arbiter_combined_out_valid_skid_reg;
      __t__multistream_payload_i__0_reg <= t__multistream_payload_i__0_data_valid_load_en ? t__multistream_payload_i__0 : __t__multistream_payload_i__0_reg;
      __t__multistream_payload_i__0_skid_reg <= t__multistream_payload_i__0_skid_data_load_en ? __t__multistream_payload_i__0_reg : __t__multistream_payload_i__0_skid_reg;
      __t__multistream_payload_i__0_valid_reg <= t__multistream_payload_i__0_data_valid_load_en__1 ? t__multistream_payload_i__0_vld : __t__multistream_payload_i__0_valid_reg;
      __t__multistream_payload_i__0_valid_skid_reg <= t__multistream_payload_i__0_skid_valid_load_en ? t__multistream_payload_i__0_from_skid_rdy : __t__multistream_payload_i__0_valid_skid_reg;
      __t__multistream_payload_i__1_reg <= t__multistream_payload_i__1_data_valid_load_en ? t__multistream_payload_i__1 : __t__multistream_payload_i__1_reg;
      __t__multistream_payload_i__1_skid_reg <= t__multistream_payload_i__1_skid_data_load_en ? __t__multistream_payload_i__1_reg : __t__multistream_payload_i__1_skid_reg;
      __t__multistream_payload_i__1_valid_reg <= t__multistream_payload_i__1_data_valid_load_en__1 ? t__multistream_payload_i__1_vld : __t__multistream_payload_i__1_valid_reg;
      __t__multistream_payload_i__1_valid_skid_reg <= t__multistream_payload_i__1_skid_valid_load_en ? t__multistream_payload_i__1_from_skid_rdy : __t__multistream_payload_i__1_valid_skid_reg;
      __t__multistream_payload_o__0_reg <= t__multistream_payload_o__0_load_en ? pld : __t__multistream_payload_o__0_reg;
      __t__multistream_payload_o__0_valid_reg <= t__multistream_payload_o__0_valid_load_en ? __t__multistream_payload_o__0_not_has_been_sent : __t__multistream_payload_o__0_valid_reg;
      __t__arbiter_payload_type_two_i_reg <= t__arbiter_payload_type_two_i_load_en ? arb_payload_in : __t__arbiter_payload_type_two_i_reg;
      __t__arbiter_payload_type_two_i_valid_reg <= t__arbiter_payload_type_two_i_valid_load_en ? __t__arbiter_payload_type_two_i_not_has_been_sent : __t__arbiter_payload_type_two_i_valid_reg;
      __t__arbiter_i_valid_reg <= t__arbiter_i_valid_load_en ? arb_payload_valid : __t__arbiter_i_valid_reg;
      __t__arbiter_i_valid_valid_reg <= t__arbiter_i_valid_valid_load_en ? __t__arbiter_i_valid_not_has_been_sent : __t__arbiter_i_valid_valid_reg;
      __t__arbiter_rotate_offset_reg <= t__arbiter_rotate_offset_load_en ? extended___state_3 : __t__arbiter_rotate_offset_reg;
      __t__arbiter_rotate_offset_valid_reg <= t__arbiter_rotate_offset_valid_load_en ? __t__arbiter_rotate_offset_not_has_been_sent : __t__arbiter_rotate_offset_valid_reg;
      __t__multistream_payload_o__1_reg <= t__multistream_payload_o__1_load_en ? pld__1 : __t__multistream_payload_o__1_reg;
      __t__multistream_payload_o__1_valid_reg <= t__multistream_payload_o__1_valid_load_en ? __t__multistream_payload_o__1_not_has_been_sent : __t__multistream_payload_o__1_valid_reg;
    end
  end
  assign t__arbiter_combined_out_rdy = t__arbiter_combined_out_from_skid_rdy;
  assign t__arbiter_i_valid = {__t__arbiter_i_valid_reg[1], __t__arbiter_i_valid_reg[0]};
  assign t__arbiter_i_valid_vld = __t__arbiter_i_valid_valid_reg;
  assign t__arbiter_payload_type_two_i = {__t__arbiter_payload_type_two_i_reg[1], __t__arbiter_payload_type_two_i_reg[0]};
  assign t__arbiter_payload_type_two_i_vld = __t__arbiter_payload_type_two_i_valid_reg;
  assign t__arbiter_rotate_offset = __t__arbiter_rotate_offset_reg;
  assign t__arbiter_rotate_offset_vld = __t__arbiter_rotate_offset_valid_reg;
  assign t__multistream_payload_i__0_rdy = t__multistream_payload_i__0_from_skid_rdy;
  assign t__multistream_payload_i__1_rdy = t__multistream_payload_i__1_from_skid_rdy;
  assign t__multistream_payload_o__0 = __t__multistream_payload_o__0_reg;
  assign t__multistream_payload_o__0_vld = __t__multistream_payload_o__0_valid_reg;
  assign t__multistream_payload_o__1 = __t__multistream_payload_o__1_reg;
  assign t__multistream_payload_o__1_vld = __t__multistream_payload_o__1_valid_reg;
  `ifdef ASSERT_ON
  ____state_2__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_1382))) or_1382) else $fatal(0, "More than one next_value fired for state element: __state_2");
  `endif  // ASSERT_ON
endmodule
