`default_nettype none
module __t__vector_loader_0_next(
  input wire clk,
  input wire rst,
  input wire t__hbm_vector_addr_rdy,
  input wire [63:0] t__hbm_vector_payload,
  input wire t__hbm_vector_payload_vld,
  input wire [31:0] t__num_matrix_cols,
  input wire t__num_matrix_cols_vld,
  input wire t__vector_payload_one__0_rdy,
  output wire [31:0] t__hbm_vector_addr,
  output wire t__hbm_vector_addr_vld,
  output wire t__hbm_vector_payload_rdy,
  output wire t__num_matrix_cols_rdy,
  output wire [95:0] t__vector_payload_one__0,
  output wire t__vector_payload_one__0_vld
);
  wire [31:0] __t__hbm_vector_payload_reg_init[2];
  assign __t__hbm_vector_payload_reg_init = '{32'h0000_0000, 32'h0000_0000};
  wire [31:0] __t__hbm_vector_payload_skid_reg_init[2];
  assign __t__hbm_vector_payload_skid_reg_init = '{32'h0000_0000, 32'h0000_0000};
  wire [31:0] literal_1863[2];
  assign literal_1863 = '{32'h0000_0000, 32'h0000_0000};
  wire [31:0] t__hbm_vector_payload_unflattened[2];
  assign t__hbm_vector_payload_unflattened[0] = t__hbm_vector_payload[31:0];
  assign t__hbm_vector_payload_unflattened[1] = t__hbm_vector_payload[63:32];
  reg [4:0] ____state_0;
  reg [31:0] ____state_5;
  reg [31:0] ____state_3;
  reg [29:0] ____state_1;
  reg [1:0] ____state_4;
  reg [31:0] ____state_7_0;
  reg [31:0] ____state_7_1;
  reg [2:0] ____state_2;
  reg [31:0] __t__num_matrix_cols_reg;
  reg [31:0] __t__num_matrix_cols_skid_reg;
  reg __t__num_matrix_cols_valid_reg;
  reg __t__num_matrix_cols_valid_skid_reg;
  reg [31:0] __t__hbm_vector_payload_reg[2];
  reg [31:0] __t__hbm_vector_payload_skid_reg[2];
  reg __t__hbm_vector_payload_valid_reg;
  reg __t__hbm_vector_payload_valid_skid_reg;
  reg [31:0] __t__hbm_vector_addr_reg;
  reg __t__hbm_vector_addr_valid_reg;
  reg [95:0] __t__vector_payload_one__0_reg;
  reg __t__vector_payload_one__0_valid_reg;
  wire [4:0] unexpand_for_next_value_414_0__1_case_6;
  wire [4:0] unexpand_for_next_value_414_0__1_case_2;
  wire nmc_rx;
  wire hvp_rx;
  wire [31:0] new_state;
  wire [4:0] unexpand_for_next_value_414_0__1_case_0;
  wire [4:0] unexpand_for_next_value_414_0__1_case_5_case_1;
  wire [4:0] unexpand_for_next_value_414_0__1_case_4_case_1;
  wire [4:0] unexpand_for_next_value_414_0__1_case_3;
  wire [31:0] new_cur_part_index__1;
  wire [31:0] new_cur_col_part;
  wire [31:0] t__num_matrix_cols_select__1;
  wire [4:0] unexpand_for_next_value_414_0__1_case_1;
  wire st4_1_case_cmp;
  wire st0_6_case_cmp;
  wire st0_5_case_cmp;
  wire st0_4_case_cmp;
  wire [29:0] leading_bits___state_4;
  wire [31:0] t__num_matrix_cols_select;
  wire [30:0] add_1809;
  wire p0_all_active_inputs_valid;
  wire hva_tx;
  wire t__hbm_vector_addr_valid_inv;
  wire vpo_tx;
  wire t__vector_payload_one__0_valid_inv;
  wire eq_1811;
  wire eq_1812;
  wire eq_1815;
  wire __t__hbm_vector_addr_vld_buf;
  wire t__hbm_vector_addr_valid_load_en;
  wire __t__vector_payload_one__0_vld_buf;
  wire t__vector_payload_one__0_valid_load_en;
  wire new_state__4_0_case_cmp;
  wire new_state__5_0_case_cmp;
  wire new_num_col_last_part_0_case_cmp;
  wire new_num_payloads_1_case_cmp;
  wire t__hbm_vector_addr_load_en;
  wire t__vector_payload_one__0_load_en;
  wire and_1835;
  wire and_1836;
  wire and_1837;
  wire and_1838;
  wire and_1839;
  wire nor_1840;
  wire nor_1841;
  wire and_1842;
  wire [1:0] ____state_3__next_value_predicates;
  wire [1:0] ____state_5__next_value_predicates;
  wire [8:0] ____state_0__next_value_predicates;
  wire [1:0] ____state_2__next_value_predicates;
  wire [1:0] ____state_4__next_value_predicates;
  wire p0_all_active_outputs_ready;
  wire [2:0] one_hot_1854;
  wire [2:0] one_hot_1855;
  wire [9:0] one_hot_1856;
  wire [2:0] one_hot_1857;
  wire [2:0] one_hot_1858;
  wire p0_stage_done;
  wire [3:0] concat_1852;
  wire t__num_matrix_cols_from_skid_rdy;
  wire and_2017;
  wire t__hbm_vector_payload_from_skid_rdy;
  wire and_2010;
  wire [30:0] add_1831;
  wire [4:0] one_hot_2089;
  wire and_1950;
  wire and_1957;
  wire [31:0] t__hbm_vector_payload_select__1[2];
  wire t__num_matrix_cols_data_valid_load_en;
  wire t__num_matrix_cols_to_is_not_rdy;
  wire t__hbm_vector_payload_data_valid_load_en;
  wire t__hbm_vector_payload_to_is_not_rdy;
  wire [1:0] leading_bits___state_1;
  wire ____state_3__at_most_one_next_value;
  wire ____state_5__at_most_one_next_value;
  wire ____state_0__at_most_one_next_value;
  wire ____state_2__at_most_one_next_value;
  wire ____state_4__at_most_one_next_value;
  wire [1:0] concat_1953;
  wire [31:0] new_cur_col;
  wire [1:0] concat_1960;
  wire [31:0] t__hbm_vector_payload_select[2];
  wire [8:0] concat_1980;
  wire [31:0] add_1887;
  wire [1:0] concat_1990;
  wire [2:0] unexpand_for_next_value_414_2__1_case_0_case_1;
  wire [2:0] unexpand_for_next_value_414_2__1_case_0_case_0;
  wire [1:0] concat_1997;
  wire [1:0] unexpand_for_next_value_414_4__1_case_1_case_1;
  wire [1:0] unexpand_for_next_value_414_4__1_case_1_case_0;
  wire t__num_matrix_cols_data_is_sent_to;
  wire t__num_matrix_cols_skid_data_load_en;
  wire t__num_matrix_cols_skid_valid_set_zero;
  wire t__hbm_vector_payload_data_is_sent_to;
  wire t__hbm_vector_payload_skid_data_load_en;
  wire t__hbm_vector_payload_skid_valid_set_zero;
  wire or_2096;
  wire or_2098;
  wire or_2100;
  wire or_2102;
  wire or_2104;
  wire [31:0] one_hot_sel_1954;
  wire and_2005;
  wire [31:0] one_hot_sel_1961;
  wire and_2008;
  wire [31:0] array_index_1912;
  wire [31:0] array_index_1913;
  wire [4:0] one_hot_sel_1981;
  wire and_2015;
  wire [29:0] unexpand_for_next_value_414_1__1_case_0;
  wire [2:0] one_hot_sel_1991;
  wire and_2020;
  wire [1:0] one_hot_sel_1998;
  wire and_2023;
  wire t__num_matrix_cols_data_valid_load_en__1;
  wire t__num_matrix_cols_skid_valid_load_en;
  wire t__hbm_vector_payload_data_valid_load_en__1;
  wire t__hbm_vector_payload_skid_valid_load_en;
  wire [31:0] requested_addr;
  wire [95:0] __t__vector_payload_one__0_buf;
  wire or_2106;
  assign unexpand_for_next_value_414_0__1_case_6 = 5'h00;
  assign unexpand_for_next_value_414_0__1_case_2 = 5'h15;
  assign nmc_rx = ____state_0 == unexpand_for_next_value_414_0__1_case_6;
  assign hvp_rx = ____state_0 == unexpand_for_next_value_414_0__1_case_2;
  assign new_state = 32'h0000_0001;
  assign unexpand_for_next_value_414_0__1_case_0 = 5'h01;
  assign unexpand_for_next_value_414_0__1_case_5_case_1 = 5'h04;
  assign unexpand_for_next_value_414_0__1_case_4_case_1 = 5'h1e;
  assign unexpand_for_next_value_414_0__1_case_3 = 5'h16;
  assign new_cur_part_index__1 = ____state_5 + new_state;
  assign new_cur_col_part = ____state_3 + new_state;
  assign t__num_matrix_cols_select__1 = __t__num_matrix_cols_valid_skid_reg ? __t__num_matrix_cols_skid_reg : __t__num_matrix_cols_reg;
  assign unexpand_for_next_value_414_0__1_case_1 = 5'h14;
  assign st4_1_case_cmp = ____state_0 == unexpand_for_next_value_414_0__1_case_0;
  assign st0_6_case_cmp = ____state_0 == unexpand_for_next_value_414_0__1_case_5_case_1;
  assign st0_5_case_cmp = ____state_0 == unexpand_for_next_value_414_0__1_case_4_case_1;
  assign st0_4_case_cmp = ____state_0 == unexpand_for_next_value_414_0__1_case_3;
  assign leading_bits___state_4 = 30'h0000_0000;
  assign t__num_matrix_cols_select = nmc_rx ? t__num_matrix_cols_select__1 : 32'h0000_0000;
  assign add_1809 = {1'h0, ____state_1} + 31'h7fff_ffff;
  assign p0_all_active_inputs_valid = (~nmc_rx | __t__num_matrix_cols_valid_reg | __t__num_matrix_cols_valid_skid_reg) & (~hvp_rx | __t__hbm_vector_payload_valid_reg | __t__hbm_vector_payload_valid_skid_reg);
  assign hva_tx = ____state_0 == unexpand_for_next_value_414_0__1_case_1;
  assign t__hbm_vector_addr_valid_inv = ~__t__hbm_vector_addr_valid_reg;
  assign vpo_tx = st4_1_case_cmp | st0_6_case_cmp | st0_5_case_cmp | st0_4_case_cmp;
  assign t__vector_payload_one__0_valid_inv = ~__t__vector_payload_one__0_valid_reg;
  assign eq_1811 = new_cur_part_index__1[31:2] == leading_bits___state_4;
  assign eq_1812 = ____state_4 == new_cur_part_index__1[1:0];
  assign eq_1815 = ____state_1 == new_cur_col_part[29:0];
  assign __t__hbm_vector_addr_vld_buf = p0_all_active_inputs_valid & hva_tx;
  assign t__hbm_vector_addr_valid_load_en = t__hbm_vector_addr_rdy | t__hbm_vector_addr_valid_inv;
  assign __t__vector_payload_one__0_vld_buf = p0_all_active_inputs_valid & vpo_tx;
  assign t__vector_payload_one__0_valid_load_en = t__vector_payload_one__0_rdy | t__vector_payload_one__0_valid_inv;
  assign new_state__4_0_case_cmp = ~(eq_1811 & eq_1812);
  assign new_state__5_0_case_cmp = ~(~new_cur_col_part[30] & ~new_cur_col_part[31] & eq_1815);
  assign new_num_col_last_part_0_case_cmp = t__num_matrix_cols_select[0] | t__num_matrix_cols_select[1];
  assign new_num_payloads_1_case_cmp = ____state_3 == {{1{add_1809[30]}}, add_1809};
  assign t__hbm_vector_addr_load_en = __t__hbm_vector_addr_vld_buf & t__hbm_vector_addr_valid_load_en;
  assign t__vector_payload_one__0_load_en = __t__vector_payload_one__0_vld_buf & t__vector_payload_one__0_valid_load_en;
  assign and_1835 = st0_4_case_cmp & new_state__4_0_case_cmp;
  assign and_1836 = st0_4_case_cmp & eq_1811 & eq_1812;
  assign and_1837 = st0_5_case_cmp & new_state__5_0_case_cmp;
  assign and_1838 = st0_5_case_cmp & ~(new_cur_col_part[30] | new_cur_col_part[31]) & eq_1815;
  assign and_1839 = nmc_rx & new_num_col_last_part_0_case_cmp;
  assign nor_1840 = ~(~nmc_rx | t__num_matrix_cols_select[0] | t__num_matrix_cols_select[1]);
  assign nor_1841 = ~(~st4_1_case_cmp | new_num_payloads_1_case_cmp);
  assign and_1842 = st4_1_case_cmp & new_num_payloads_1_case_cmp;
  assign ____state_3__next_value_predicates = {nmc_rx, st0_5_case_cmp};
  assign ____state_5__next_value_predicates = {st4_1_case_cmp, st0_4_case_cmp};
  assign ____state_0__next_value_predicates = {nmc_rx, st4_1_case_cmp, hva_tx, hvp_rx, st0_6_case_cmp, and_1835, and_1836, and_1837, and_1838};
  assign ____state_2__next_value_predicates = {and_1839, nor_1840};
  assign ____state_4__next_value_predicates = {nor_1841, and_1842};
  assign p0_all_active_outputs_ready = (~hva_tx | t__hbm_vector_addr_load_en) & (~vpo_tx | t__vector_payload_one__0_load_en);
  assign one_hot_1854 = {____state_3__next_value_predicates[1:0] == 2'h0, ____state_3__next_value_predicates[1] && !____state_3__next_value_predicates[0], ____state_3__next_value_predicates[0]};
  assign one_hot_1855 = {____state_5__next_value_predicates[1:0] == 2'h0, ____state_5__next_value_predicates[1] && !____state_5__next_value_predicates[0], ____state_5__next_value_predicates[0]};
  assign one_hot_1856 = {____state_0__next_value_predicates[8:0] == 9'h000, ____state_0__next_value_predicates[8] && ____state_0__next_value_predicates[7:0] == 8'h00, ____state_0__next_value_predicates[7] && ____state_0__next_value_predicates[6:0] == 7'h00, ____state_0__next_value_predicates[6] && ____state_0__next_value_predicates[5:0] == 6'h00, ____state_0__next_value_predicates[5] && ____state_0__next_value_predicates[4:0] == 5'h00, ____state_0__next_value_predicates[4] && ____state_0__next_value_predicates[3:0] == 4'h0, ____state_0__next_value_predicates[3] && ____state_0__next_value_predicates[2:0] == 3'h0, ____state_0__next_value_predicates[2] && ____state_0__next_value_predicates[1:0] == 2'h0, ____state_0__next_value_predicates[1] && !____state_0__next_value_predicates[0], ____state_0__next_value_predicates[0]};
  assign one_hot_1857 = {____state_2__next_value_predicates[1:0] == 2'h0, ____state_2__next_value_predicates[1] && !____state_2__next_value_predicates[0], ____state_2__next_value_predicates[0]};
  assign one_hot_1858 = {____state_4__next_value_predicates[1:0] == 2'h0, ____state_4__next_value_predicates[1] && !____state_4__next_value_predicates[0], ____state_4__next_value_predicates[0]};
  assign p0_stage_done = p0_all_active_inputs_valid & p0_all_active_outputs_ready;
  assign concat_1852 = {st0_6_case_cmp, st0_5_case_cmp, st0_4_case_cmp, st4_1_case_cmp};
  assign t__num_matrix_cols_from_skid_rdy = ~__t__num_matrix_cols_valid_skid_reg;
  assign and_2017 = nmc_rx & p0_stage_done;
  assign t__hbm_vector_payload_from_skid_rdy = ~__t__hbm_vector_payload_valid_skid_reg;
  assign and_2010 = hvp_rx & p0_stage_done;
  assign add_1831 = ____state_5[31:1] + {1'h0, ____state_3[29:0]};
  assign one_hot_2089 = {concat_1852[3:0] == 4'h0, concat_1852[3] && concat_1852[2:0] == 3'h0, concat_1852[2] && concat_1852[1:0] == 2'h0, concat_1852[1] && !concat_1852[0], concat_1852[0]};
  assign and_1950 = nmc_rx & p0_stage_done;
  assign and_1957 = st4_1_case_cmp & p0_stage_done;
  assign t__hbm_vector_payload_select__1 = __t__hbm_vector_payload_valid_skid_reg == 1'h0 ? __t__hbm_vector_payload_reg : __t__hbm_vector_payload_skid_reg;
  assign t__num_matrix_cols_data_valid_load_en = t__num_matrix_cols_vld & t__num_matrix_cols_from_skid_rdy;
  assign t__num_matrix_cols_to_is_not_rdy = ~and_2017;
  assign t__hbm_vector_payload_data_valid_load_en = t__hbm_vector_payload_vld & t__hbm_vector_payload_from_skid_rdy;
  assign t__hbm_vector_payload_to_is_not_rdy = ~and_2010;
  assign leading_bits___state_1 = 2'h0;
  assign ____state_3__at_most_one_next_value = nmc_rx == one_hot_1854[1] & st0_5_case_cmp == one_hot_1854[0];
  assign ____state_5__at_most_one_next_value = st4_1_case_cmp == one_hot_1855[1] & st0_4_case_cmp == one_hot_1855[0];
  assign ____state_0__at_most_one_next_value = nmc_rx == one_hot_1856[8] & st4_1_case_cmp == one_hot_1856[7] & hva_tx == one_hot_1856[6] & hvp_rx == one_hot_1856[5] & st0_6_case_cmp == one_hot_1856[4] & and_1835 == one_hot_1856[3] & and_1836 == one_hot_1856[2] & and_1837 == one_hot_1856[1] & and_1838 == one_hot_1856[0];
  assign ____state_2__at_most_one_next_value = and_1839 == one_hot_1857[1] & nor_1840 == one_hot_1857[0];
  assign ____state_4__at_most_one_next_value = nor_1841 == one_hot_1858[1] & and_1842 == one_hot_1858[0];
  assign concat_1953 = {and_1950, st0_5_case_cmp & p0_stage_done};
  assign new_cur_col = 32'h0000_0000;
  assign concat_1960 = {and_1957, st0_4_case_cmp & p0_stage_done};
  assign t__hbm_vector_payload_select = hvp_rx == 1'h0 ? literal_1863 : t__hbm_vector_payload_select__1;
  assign concat_1980 = {and_1950, and_1957, hva_tx & p0_stage_done, hvp_rx & p0_stage_done, st0_6_case_cmp & p0_stage_done, and_1835 & p0_stage_done, and_1836 & p0_stage_done, and_1837 & p0_stage_done, and_1838 & p0_stage_done};
  assign add_1887 = t__num_matrix_cols_select + 32'h0000_0003;
  assign concat_1990 = {and_1839 & p0_stage_done, nor_1840 & p0_stage_done};
  assign unexpand_for_next_value_414_2__1_case_0_case_1 = 3'h4;
  assign unexpand_for_next_value_414_2__1_case_0_case_0 = {1'h0, t__num_matrix_cols_select[1:0]};
  assign concat_1997 = {nor_1841 & p0_stage_done, and_1842 & p0_stage_done};
  assign unexpand_for_next_value_414_4__1_case_1_case_1 = ____state_2[2:1];
  assign unexpand_for_next_value_414_4__1_case_1_case_0 = 2'h2;
  assign t__num_matrix_cols_data_is_sent_to = __t__num_matrix_cols_valid_reg & and_2017 & t__num_matrix_cols_from_skid_rdy;
  assign t__num_matrix_cols_skid_data_load_en = __t__num_matrix_cols_valid_reg & t__num_matrix_cols_data_valid_load_en & t__num_matrix_cols_to_is_not_rdy;
  assign t__num_matrix_cols_skid_valid_set_zero = __t__num_matrix_cols_valid_skid_reg & and_2017;
  assign t__hbm_vector_payload_data_is_sent_to = __t__hbm_vector_payload_valid_reg & and_2010 & t__hbm_vector_payload_from_skid_rdy;
  assign t__hbm_vector_payload_skid_data_load_en = __t__hbm_vector_payload_valid_reg & t__hbm_vector_payload_data_valid_load_en & t__hbm_vector_payload_to_is_not_rdy;
  assign t__hbm_vector_payload_skid_valid_set_zero = __t__hbm_vector_payload_valid_skid_reg & and_2010;
  assign or_2096 = ~p0_stage_done | ____state_3__at_most_one_next_value | rst;
  assign or_2098 = ~p0_stage_done | ____state_5__at_most_one_next_value | rst;
  assign or_2100 = ~p0_stage_done | ____state_0__at_most_one_next_value | rst;
  assign or_2102 = ~p0_stage_done | ____state_2__at_most_one_next_value | rst;
  assign or_2104 = ~p0_stage_done | ____state_4__at_most_one_next_value | rst;
  assign one_hot_sel_1954 = new_cur_col_part & {32{concat_1953[0]}} | new_cur_col & {32{concat_1953[1]}};
  assign and_2005 = (nmc_rx | st0_5_case_cmp) & p0_stage_done;
  assign one_hot_sel_1961 = new_cur_part_index__1 & {32{concat_1960[0]}} | new_cur_col & {32{concat_1960[1]}};
  assign and_2008 = (st4_1_case_cmp | st0_4_case_cmp) & p0_stage_done;
  assign array_index_1912 = t__hbm_vector_payload_select[1'h0];
  assign array_index_1913 = t__hbm_vector_payload_select[1'h1];
  assign one_hot_sel_1981 = unexpand_for_next_value_414_0__1_case_5_case_1 & {5{concat_1980[0]}} | unexpand_for_next_value_414_0__1_case_0 & {5{concat_1980[1]}} | unexpand_for_next_value_414_0__1_case_4_case_1 & {5{concat_1980[2]}} | unexpand_for_next_value_414_0__1_case_1 & {5{concat_1980[3]}} | unexpand_for_next_value_414_0__1_case_6 & {5{concat_1980[4]}} | unexpand_for_next_value_414_0__1_case_3 & {5{concat_1980[5]}} | unexpand_for_next_value_414_0__1_case_2 & {5{concat_1980[6]}} | unexpand_for_next_value_414_0__1_case_1 & {5{concat_1980[7]}} | unexpand_for_next_value_414_0__1_case_0 & {5{concat_1980[8]}};
  assign and_2015 = (nmc_rx | st4_1_case_cmp | hva_tx | hvp_rx | st0_6_case_cmp | and_1835 | and_1836 | and_1837 | and_1838) & p0_stage_done;
  assign unexpand_for_next_value_414_1__1_case_0 = add_1887[31:2];
  assign one_hot_sel_1991 = unexpand_for_next_value_414_2__1_case_0_case_1 & {3{concat_1990[0]}} | unexpand_for_next_value_414_2__1_case_0_case_0 & {3{concat_1990[1]}};
  assign and_2020 = (and_1839 | nor_1840) & p0_stage_done;
  assign one_hot_sel_1998 = unexpand_for_next_value_414_4__1_case_1_case_1 & {2{concat_1997[0]}} | unexpand_for_next_value_414_4__1_case_1_case_0 & {2{concat_1997[1]}};
  assign and_2023 = (nor_1841 | and_1842) & p0_stage_done;
  assign t__num_matrix_cols_data_valid_load_en__1 = t__num_matrix_cols_data_is_sent_to | t__num_matrix_cols_data_valid_load_en;
  assign t__num_matrix_cols_skid_valid_load_en = t__num_matrix_cols_skid_data_load_en | t__num_matrix_cols_skid_valid_set_zero;
  assign t__hbm_vector_payload_data_valid_load_en__1 = t__hbm_vector_payload_data_is_sent_to | t__hbm_vector_payload_data_valid_load_en;
  assign t__hbm_vector_payload_skid_valid_load_en = t__hbm_vector_payload_skid_data_load_en | t__hbm_vector_payload_skid_valid_set_zero;
  assign requested_addr = {add_1831, ____state_5[0]};
  assign __t__vector_payload_one__0_buf = 96'h4000_0000_0000_0000_0000_0000 & {96{concat_1852[0]}} | {leading_bits___state_1, add_1831[28:0], ____state_5[0], ____state_7_0, ____state_7_1} & {96{concat_1852[1]}} | 96'h8000_0000_0000_0000_0000_0000 & {96{concat_1852[2]}} | 96'hc000_0000_0000_0000_0000_0000 & {96{concat_1852[3]}};
  assign or_2106 = ~p0_stage_done | concat_1852 == one_hot_2089[3:0] | rst;
  always_ff @ (posedge clk) begin
    if (rst) begin
      ____state_0 <= 5'h00;
      ____state_5 <= 32'h0000_0000;
      ____state_3 <= 32'h0000_0000;
      ____state_1 <= 30'h0000_0000;
      ____state_4 <= 2'h0;
      ____state_7_0 <= 32'h0000_0000;
      ____state_7_1 <= 32'h0000_0000;
      ____state_2 <= 3'h0;
      __t__num_matrix_cols_reg <= 32'h0000_0000;
      __t__num_matrix_cols_skid_reg <= 32'h0000_0000;
      __t__num_matrix_cols_valid_reg <= 1'h0;
      __t__num_matrix_cols_valid_skid_reg <= 1'h0;
      __t__hbm_vector_payload_reg <= __t__hbm_vector_payload_reg_init;
      __t__hbm_vector_payload_skid_reg <= __t__hbm_vector_payload_skid_reg_init;
      __t__hbm_vector_payload_valid_reg <= 1'h0;
      __t__hbm_vector_payload_valid_skid_reg <= 1'h0;
      __t__hbm_vector_addr_reg <= 32'h0000_0000;
      __t__hbm_vector_addr_valid_reg <= 1'h0;
      __t__vector_payload_one__0_reg <= 96'h0000_0000_0000_0000_0000_0000;
      __t__vector_payload_one__0_valid_reg <= 1'h0;
    end else begin
      ____state_0 <= and_2015 ? one_hot_sel_1981 : ____state_0;
      ____state_5 <= and_2008 ? one_hot_sel_1961 : ____state_5;
      ____state_3 <= and_2005 ? one_hot_sel_1954 : ____state_3;
      ____state_1 <= and_2017 ? unexpand_for_next_value_414_1__1_case_0 : ____state_1;
      ____state_4 <= and_2023 ? one_hot_sel_1998 : ____state_4;
      ____state_7_0 <= and_2010 ? array_index_1912 : ____state_7_0;
      ____state_7_1 <= and_2010 ? array_index_1913 : ____state_7_1;
      ____state_2 <= and_2020 ? one_hot_sel_1991 : ____state_2;
      __t__num_matrix_cols_reg <= t__num_matrix_cols_data_valid_load_en ? t__num_matrix_cols : __t__num_matrix_cols_reg;
      __t__num_matrix_cols_skid_reg <= t__num_matrix_cols_skid_data_load_en ? __t__num_matrix_cols_reg : __t__num_matrix_cols_skid_reg;
      __t__num_matrix_cols_valid_reg <= t__num_matrix_cols_data_valid_load_en__1 ? t__num_matrix_cols_vld : __t__num_matrix_cols_valid_reg;
      __t__num_matrix_cols_valid_skid_reg <= t__num_matrix_cols_skid_valid_load_en ? t__num_matrix_cols_from_skid_rdy : __t__num_matrix_cols_valid_skid_reg;
      __t__hbm_vector_payload_reg <= t__hbm_vector_payload_data_valid_load_en ? t__hbm_vector_payload_unflattened : __t__hbm_vector_payload_reg;
      __t__hbm_vector_payload_skid_reg <= t__hbm_vector_payload_skid_data_load_en ? __t__hbm_vector_payload_reg : __t__hbm_vector_payload_skid_reg;
      __t__hbm_vector_payload_valid_reg <= t__hbm_vector_payload_data_valid_load_en__1 ? t__hbm_vector_payload_vld : __t__hbm_vector_payload_valid_reg;
      __t__hbm_vector_payload_valid_skid_reg <= t__hbm_vector_payload_skid_valid_load_en ? t__hbm_vector_payload_from_skid_rdy : __t__hbm_vector_payload_valid_skid_reg;
      __t__hbm_vector_addr_reg <= t__hbm_vector_addr_load_en ? requested_addr : __t__hbm_vector_addr_reg;
      __t__hbm_vector_addr_valid_reg <= t__hbm_vector_addr_valid_load_en ? __t__hbm_vector_addr_vld_buf : __t__hbm_vector_addr_valid_reg;
      __t__vector_payload_one__0_reg <= t__vector_payload_one__0_load_en ? __t__vector_payload_one__0_buf : __t__vector_payload_one__0_reg;
      __t__vector_payload_one__0_valid_reg <= t__vector_payload_one__0_valid_load_en ? __t__vector_payload_one__0_vld_buf : __t__vector_payload_one__0_valid_reg;
    end
  end
  assign t__hbm_vector_addr = __t__hbm_vector_addr_reg;
  assign t__hbm_vector_addr_vld = __t__hbm_vector_addr_valid_reg;
  assign t__hbm_vector_payload_rdy = t__hbm_vector_payload_from_skid_rdy;
  assign t__num_matrix_cols_rdy = t__num_matrix_cols_from_skid_rdy;
  assign t__vector_payload_one__0 = __t__vector_payload_one__0_reg;
  assign t__vector_payload_one__0_vld = __t__vector_payload_one__0_valid_reg;
  `ifdef ASSERT_ON
  ____state_3__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2096))) or_2096) else $fatal(0, "More than one next_value fired for state element: __state_3");
  ____state_5__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2098))) or_2098) else $fatal(0, "More than one next_value fired for state element: __state_5");
  ____state_0__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2100))) or_2100) else $fatal(0, "More than one next_value fired for state element: __state_0");
  ____state_2__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2102))) or_2102) else $fatal(0, "More than one next_value fired for state element: __state_2");
  ____state_4__at_most_one_next_value_assert: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2104))) or_2104) else $fatal(0, "More than one next_value fired for state element: __state_4");
  __xls_invariant___t__vector_payload_one__0_buf_selector_one_hot_A: assert property (@(posedge clk) disable iff ($sampled(rst !== 1'h0 || $isunknown(or_2106))) or_2106) else $fatal(0, "Selector concat.1852 was expected to be one-hot, and is not.");
  `endif  // ASSERT_ON
endmodule
`default_nettype wire
